<?php

return [
    'tools' => [
        'juros-simples' => [
            'slug' => 'juros-simples',
            'legacy_file' => 'juros-simples.php',
            'page_key' => 'tool:juros-simples',
            'name' => 'Calculadora de Juros Simples',
            'short_name' => 'Juros Simples',
            'category' => 'Finanças',
            'category_key' => 'financas',
            'icon' => '💰',
            'gradient' => 'linear-gradient(135deg,#e8f0fe,#c5d8ff)',
            'excerpt' => 'Calcule o valor dos juros simples, montante final e taxa total de qualquer operação.',
            'lead' => 'Calcule o montante final, os juros totais e o valor futuro de qualquer operação com juros simples. Rápido e gratuito.',
            'keywords' => 'calculadora juros simples, calcular juros simples online, fórmula juros simples, montante juros simples',
            'schema_type' => 'FinancialProduct',
            'priority' => '0.8',
            'changefreq' => 'monthly',
            'related' => ['juros-compostos', 'simulador-financiamento', 'calculadora-porcentagem'],
        ],
        'juros-compostos' => [
            'slug' => 'juros-compostos',
            'legacy_file' => 'juros-compostos.php',
            'page_key' => 'tool:juros-compostos',
            'name' => 'Calculadora de Juros Compostos',
            'short_name' => 'Juros Compostos',
            'category' => 'Finanças',
            'category_key' => 'financas',
            'icon' => '📈',
            'gradient' => 'linear-gradient(135deg,#e6f9f4,#b8f0e0)',
            'excerpt' => 'Simule investimentos com juros compostos e descubra quanto o dinheiro pode render no tempo.',
            'lead' => 'Simule o crescimento de investimentos com juros compostos. Descubra quanto seu dinheiro pode render.',
            'keywords' => 'juros compostos, calculadora juros compostos, juros sobre juros, simulador investimento',
            'schema_type' => 'FinancialProduct',
            'priority' => '0.8',
            'changefreq' => 'monthly',
            'related' => ['juros-simples', 'simulador-financiamento', 'calculadora-porcentagem'],
        ],
        'simulador-financiamento' => [
            'slug' => 'simulador-financiamento',
            'legacy_file' => 'simulador-financiamento.php',
            'page_key' => 'tool:simulador-financiamento',
            'name' => 'Simulador de Financiamento',
            'short_name' => 'Financiamento',
            'category' => 'Finanças',
            'category_key' => 'financas',
            'icon' => '🏠',
            'gradient' => 'linear-gradient(135deg,#fff3e8,#ffd8b8)',
            'excerpt' => 'Simule financiamentos, compare parcelas e entenda o custo total do crédito antes de contratar.',
            'lead' => 'Simule financiamentos e descubra o valor das parcelas, juros totais pagos e o custo total do crédito.',
            'keywords' => 'simulador de financiamento, calcular parcelas, financiamento price, financiamento sac',
            'schema_type' => 'FinancialProduct',
            'priority' => '0.8',
            'changefreq' => 'monthly',
            'related' => ['juros-compostos', 'juros-simples', 'calculadora-porcentagem'],
        ],
        'calculadora-porcentagem' => [
            'slug' => 'calculadora-porcentagem',
            'legacy_file' => 'calculadora-porcentagem.php',
            'page_key' => 'tool:calculadora-porcentagem',
            'name' => 'Calculadora de Porcentagem',
            'short_name' => 'Porcentagem',
            'category' => 'Matemática',
            'category_key' => 'matematica',
            'icon' => '%',
            'gradient' => 'linear-gradient(135deg,#fef3e8,#fde0bd)',
            'excerpt' => 'Calcule desconto, aumento e variações percentuais com respostas instantâneas.',
            'lead' => 'Calcule porcentagens, descontos, aumentos e variações percentuais de forma simples e rápida.',
            'keywords' => 'calculadora de porcentagem, calcular desconto online, aumento percentual, variação percentual',
            'schema_type' => 'WebApplication',
            'priority' => '0.8',
            'changefreq' => 'monthly',
            'related' => ['juros-simples', 'juros-compostos', 'simulador-financiamento'],
        ],
        'calculadora-idade' => [
            'slug' => 'calculadora-idade',
            'legacy_file' => 'calculadora-idade.php',
            'page_key' => 'tool:calculadora-idade',
            'name' => 'Calculadora de Idade',
            'short_name' => 'Calculadora de Idade',
            'category' => 'Datas',
            'category_key' => 'datas',
            'icon' => '🎂',
            'gradient' => 'linear-gradient(135deg,#fce8ff,#f0c8ff)',
            'excerpt' => 'Descubra idade exata em anos, meses, dias e o próximo aniversário em segundos.',
            'lead' => 'Descubra sua idade exata em anos, meses, dias e horas. Saiba também quando é o próximo aniversário.',
            'keywords' => 'calculadora de idade, idade exata online, calcular idade por data de nascimento',
            'schema_type' => 'WebApplication',
            'priority' => '0.8',
            'changefreq' => 'monthly',
            'related' => ['contador-caracteres', 'conversor-texto', 'gerador-nomes'],
        ],
        'gerador-nomes' => [
            'slug' => 'gerador-nomes',
            'legacy_file' => 'gerador-nomes.php',
            'page_key' => 'tool:gerador-nomes',
            'name' => 'Gerador de Nomes',
            'short_name' => 'Gerador de Nomes',
            'category' => 'Criatividade',
            'category_key' => 'geradores',
            'icon' => '👤',
            'gradient' => 'linear-gradient(135deg,#e8f5e9,#c8e6c9)',
            'excerpt' => 'Gere nomes aleatórios para personagens, empresas e projetos com poucos cliques.',
            'lead' => 'Gere nomes aleatórios para personagens, empresas ou projetos. Masculino, feminino ou neutro.',
            'keywords' => 'gerador de nomes, nomes aleatórios online, nomes para personagens, nomes para empresa',
            'schema_type' => 'WebApplication',
            'priority' => '0.8',
            'changefreq' => 'monthly',
            'related' => ['gerador-senhas', 'contador-caracteres', 'conversor-texto'],
        ],
        'gerador-senhas' => [
            'slug' => 'gerador-senhas',
            'legacy_file' => 'gerador-senhas.php',
            'page_key' => 'tool:gerador-senhas',
            'name' => 'Gerador de Senhas',
            'short_name' => 'Gerador de Senhas',
            'category' => 'Segurança',
            'category_key' => 'geradores',
            'icon' => '🔐',
            'gradient' => 'linear-gradient(135deg,#e8eaff,#c5caff)',
            'excerpt' => 'Crie senhas fortes e seguras com letras, números e símbolos personalizados.',
            'lead' => 'Crie senhas fortes e seguras com letras, números e símbolos. Personalize o tamanho e os caracteres.',
            'keywords' => 'gerador de senhas, senha forte online, criar senha segura, password generator',
            'schema_type' => 'WebApplication',
            'priority' => '0.8',
            'changefreq' => 'monthly',
            'related' => ['gerador-cpf', 'gerador-nomes', 'contador-caracteres'],
        ],
        'contador-caracteres' => [
            'slug' => 'contador-caracteres',
            'legacy_file' => 'contador-caracteres.php',
            'page_key' => 'tool:contador-caracteres',
            'name' => 'Contador de Caracteres',
            'short_name' => 'Contador de Caracteres',
            'category' => 'Texto',
            'category_key' => 'texto',
            'icon' => '🔢',
            'gradient' => 'linear-gradient(135deg,#fff8e1,#ffe082)',
            'excerpt' => 'Conte caracteres, palavras, frases e parágrafos em tempo real para SEO e redes sociais.',
            'lead' => 'Conte caracteres, palavras, frases e parágrafos de qualquer texto. Ideal para redes sociais e SEO.',
            'keywords' => 'contador de caracteres, contar palavras online, contador de texto, contador seo',
            'schema_type' => 'WebApplication',
            'priority' => '0.8',
            'changefreq' => 'monthly',
            'related' => ['conversor-texto', 'gerador-nomes', 'calculadora-idade'],
        ],
        'conversor-texto' => [
            'slug' => 'conversor-texto',
            'legacy_file' => 'conversor-texto.php',
            'page_key' => 'tool:conversor-texto',
            'name' => 'Conversor de Texto',
            'short_name' => 'Conversor de Texto',
            'category' => 'Texto',
            'category_key' => 'texto',
            'icon' => '🔄',
            'gradient' => 'linear-gradient(135deg,#e8f4fd,#b3d9f5)',
            'excerpt' => 'Converta texto para maiúsculas, minúsculas, título, slug e outros formatos úteis.',
            'lead' => 'Converta texto para maiúsculas, minúsculas, título, inverso e muito mais com apenas um clique.',
            'keywords' => 'conversor de texto, texto maiúsculo e minúsculo, criar slug online, formatar texto',
            'schema_type' => 'WebApplication',
            'priority' => '0.8',
            'changefreq' => 'monthly',
            'related' => ['contador-caracteres', 'gerador-nomes', 'gerador-senhas'],
        ],
        'gerador-cpf' => [
            'slug' => 'gerador-cpf',
            'legacy_file' => 'gerador-cpf.php',
            'page_key' => 'tool:gerador-cpf',
            'name' => 'Gerador de CPF',
            'short_name' => 'Gerador de CPF',
            'category' => 'Dev / Teste',
            'category_key' => 'geradores',
            'icon' => '🪪',
            'gradient' => 'linear-gradient(135deg,#fde8e8,#ffbbbb)',
            'excerpt' => 'Gere CPFs válidos para ambientes de teste, QA e desenvolvimento de sistemas.',
            'lead' => 'Gere CPFs válidos para fins educacionais e de desenvolvimento/teste de sistemas. Uso exclusivamente técnico.',
            'keywords' => 'gerador de cpf, cpf para teste, cpf válido desenvolvimento, gerar cpf online',
            'schema_type' => 'WebApplication',
            'priority' => '0.7',
            'changefreq' => 'monthly',
            'related' => ['gerador-senhas', 'contador-caracteres', 'conversor-texto'],
        ],
    ],
    'categories' => [
        'financas' => ['label' => 'Finanças', 'icon' => '💰'],
        'matematica' => ['label' => 'Matemática', 'icon' => '📊'],
        'texto' => ['label' => 'Texto e Produtividade', 'icon' => '📝'],
        'geradores' => ['label' => 'Geradores', 'icon' => '🎲'],
        'datas' => ['label' => 'Datas', 'icon' => '📅'],
    ],
];
