<?php

return array (
  'tools' => 
  array (
    'calculadora-aluguel-reajuste' => 
    array (
      'slug' => 'calculadora-aluguel-reajuste',
      'legacy_file' => 'calculadora-aluguel-reajuste.php',
      'page_key' => 'tool:calculadora-aluguel-reajuste',
      'name' => 'Calculadora de Reajuste de Aluguel',
      'short_name' => 'Reajuste de Aluguel',
      'category' => 'Finanças',
      'category_key' => 'financas',
      'icon' => '🏠',
      'gradient' => 'linear-gradient(135deg,#eef7ff,#d9e9ff)',
      'excerpt' => 'Ferramenta online para usar Calculadora de Reajuste de Aluguel com rapidez e praticidade.',
      'lead' => 'Simule o novo valor do aluguel após aplicar um índice ou percentual de reajuste.',
      'keywords' => 'calculadora reajuste aluguel, reajuste de aluguel online, novo valor aluguel',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
        0 => 'calculadora-correcao-monetaria',
        1 => 'calculadora-inflacao',
        2 => 'simulador-financiamento',
      ),
    ),
    'calculadora-area-circulo' => 
    array (
      'slug' => 'calculadora-area-circulo',
      'legacy_file' => 'calculadora-area-circulo.php',
      'page_key' => 'tool:calculadora-area-circulo',
      'name' => 'Calculadora de Área do Círculo',
      'short_name' => 'Área do Círculo',
      'category' => 'Matemática',
      'category_key' => 'matematica',
      'icon' => '⭕',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Calculadora de Área do Círculo com rapidez e praticidade.',
      'lead' => 'Calculadora de Área do Círculo online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'calculadora-area-circulo, ferramenta online, Calculadora de Área do Círculo',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'calculadora-area-quadrado' => 
    array (
      'slug' => 'calculadora-area-quadrado',
      'legacy_file' => 'calculadora-area-quadrado.php',
      'page_key' => 'tool:calculadora-area-quadrado',
      'name' => 'Calculadora de Área do Quadrado',
      'short_name' => 'Área do Quadrado',
      'category' => 'Matemática',
      'category_key' => 'matematica',
      'icon' => '⬜',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Calculadora de Área do Quadrado com rapidez e praticidade.',
      'lead' => 'Calculadora de Área do Quadrado online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'calculadora-area-quadrado, ferramenta online, Calculadora de Área do Quadrado',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'calculadora-area-triangulo' => 
    array (
      'slug' => 'calculadora-area-triangulo',
      'legacy_file' => 'calculadora-area-triangulo.php',
      'page_key' => 'tool:calculadora-area-triangulo',
      'name' => 'Calculadora de Área do Triângulo',
      'short_name' => 'Área do Triângulo',
      'category' => 'Matemática',
      'category_key' => 'matematica',
      'icon' => '🔺',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Calculadora de Área do Triângulo com rapidez e praticidade.',
      'lead' => 'Calculadora de Área do Triângulo online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'calculadora-area-triangulo, ferramenta online, Calculadora de Área do Triângulo',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'calculadora-break-even' => 
    array (
      'slug' => 'calculadora-break-even',
      'legacy_file' => 'calculadora-break-even.php',
      'page_key' => 'tool:calculadora-break-even',
      'name' => 'Calculadora de Break Even',
      'short_name' => 'Break Even',
      'category' => 'Finanças',
      'category_key' => 'financas',
      'icon' => '💹',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Calculadora de Break Even com rapidez e praticidade.',
      'lead' => 'Calculadora de Break Even online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'calculadora-break-even, ferramenta online, Calculadora de Break Even',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'calculadora-cagr' => 
    array (
      'slug' => 'calculadora-cagr',
      'legacy_file' => 'calculadora-cagr.php',
      'page_key' => 'tool:calculadora-cagr',
      'name' => 'Calculadora de CAGR',
      'short_name' => 'CAGR',
      'category' => 'Finanças',
      'category_key' => 'financas',
      'icon' => '📊',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Calculadora de CAGR com rapidez e praticidade.',
      'lead' => 'Calculadora de CAGR online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'calculadora-cagr, ferramenta online, Calculadora de CAGR',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'calculadora-cartao-credito' => 
    array (
      'slug' => 'calculadora-cartao-credito',
      'legacy_file' => 'calculadora-cartao-credito.php',
      'page_key' => 'tool:calculadora-cartao-credito',
      'name' => 'Calculadora de Cartão de Crédito',
      'short_name' => 'Cartão de Crédito',
      'category' => 'Finanças',
      'category_key' => 'financas',
      'icon' => '💳',
      'gradient' => 'linear-gradient(135deg,#fff7f0,#ffe4cc)',
      'excerpt' => 'Ferramenta online para usar Calculadora de Cartão de Crédito com rapidez e praticidade.',
      'lead' => 'Simule juros de cartão de crédito a partir do valor da fatura, juros mensais e quantidade de meses.',
      'keywords' => 'calculadora cartão de crédito, juros fatura, parcelamento cartão',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
        0 => 'calculadora-emprestimo',
        1 => 'calculadora-juros-atraso',
        2 => 'juros-compostos',
      ),
    ),
    'calculadora-cdi' => 
    array (
      'slug' => 'calculadora-cdi',
      'legacy_file' => 'calculadora-cdi.php',
      'page_key' => 'tool:calculadora-cdi',
      'name' => 'Calculadora de CDI',
      'short_name' => 'CDI',
      'category' => 'Finanças',
      'category_key' => 'financas',
      'icon' => '💹',
      'gradient' => 'linear-gradient(135deg,#f2f8ff,#dce9ff)',
      'excerpt' => 'Ferramenta online para usar Calculadora de CDI com rapidez e praticidade.',
      'lead' => 'Simule rendimento atrelado ao CDI usando valor investido, percentual do CDI e prazo.',
      'keywords' => 'calculadora cdi, rendimento cdi, investimento cdi',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
        0 => 'calculadora-rendimento-poupanca',
        1 => 'calculadora-investimento-mensal',
        2 => 'juros-compostos',
      ),
    ),
    'calculadora-correcao-monetaria' => 
    array (
      'slug' => 'calculadora-correcao-monetaria',
      'legacy_file' => 'calculadora-correcao-monetaria.php',
      'page_key' => 'tool:calculadora-correcao-monetaria',
      'name' => 'Calculadora de Correção Monetária',
      'short_name' => 'Correção Monetária',
      'category' => 'Finanças',
      'category_key' => 'financas',
      'icon' => '📊',
      'gradient' => 'linear-gradient(135deg,#f4f8ff,#dfe8ff)',
      'excerpt' => 'Ferramenta online para usar Calculadora de Correção Monetária com rapidez e praticidade.',
      'lead' => 'Corrija um valor aplicando uma taxa percentual para simular atualização monetária.',
      'keywords' => 'calculadora correção monetária, valor corrigido, atualização monetária',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
        0 => 'calculadora-inflacao',
        1 => 'calculadora-aluguel-reajuste',
        2 => 'calculadora-juros-atraso',
      ),
    ),
    'calculadora-desconto' => 
    array (
      'slug' => 'calculadora-desconto',
      'legacy_file' => 'calculadora-desconto.php',
      'page_key' => 'tool:calculadora-desconto',
      'name' => 'Calculadora de Desconto',
      'short_name' => 'Desconto',
      'category' => 'Finanças',
      'category_key' => 'financas',
      'icon' => '🏷️',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Calculadora de Desconto com rapidez e praticidade.',
      'lead' => 'Calculadora de Desconto online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'calculadora-desconto, ferramenta online, Calculadora de Desconto',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'calculadora-emprestimo' => 
    array (
      'slug' => 'calculadora-emprestimo',
      'legacy_file' => 'calculadora-emprestimo.php',
      'page_key' => 'tool:calculadora-emprestimo',
      'name' => 'Calculadora de Empréstimo',
      'short_name' => 'Empréstimo',
      'category' => 'Finanças',
      'category_key' => 'financas',
      'icon' => '💳',
      'gradient' => 'linear-gradient(135deg,#fff5ef,#ffe0c8)',
      'excerpt' => 'Ferramenta online para usar Calculadora de Empréstimo com rapidez e praticidade.',
      'lead' => 'Simule parcelas e valor total de um empréstimo usando taxa de juros e prazo.',
      'keywords' => 'calculadora empréstimo, parcela empréstimo, simular empréstimo',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
        0 => 'simulador-financiamento',
        1 => 'calculadora-cartao-credito',
        2 => 'calculadora-juros-atraso',
      ),
    ),
    'calculadora-fgts' => 
    array (
      'slug' => 'calculadora-fgts',
      'legacy_file' => 'calculadora-fgts.php',
      'page_key' => 'tool:calculadora-fgts',
      'name' => 'Calculadora de FGTS',
      'short_name' => 'FGTS',
      'category' => 'Finanças',
      'category_key' => 'financas',
      'icon' => '📦',
      'gradient' => 'linear-gradient(135deg,#edf9f1,#d6f0df)',
      'excerpt' => 'Ferramenta online para usar Calculadora de FGTS com rapidez e praticidade.',
      'lead' => 'Estime o depósito mensal de FGTS a partir do salário bruto do trabalhador.',
      'keywords' => 'calculadora fgts, fgts salário, depósito fgts',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
        0 => 'calculadora-inss',
        1 => 'calculadora-imposto-renda',
        2 => 'calculadora-salario-liquido',
      ),
    ),
    'calculadora-horas-trabalho' => 
    array (
      'slug' => 'calculadora-horas-trabalho',
      'legacy_file' => 'calculadora-horas-trabalho.php',
      'page_key' => 'tool:calculadora-horas-trabalho',
      'name' => 'Calculadora de Horas de Trabalho',
      'short_name' => 'Horas de Trabalho',
      'category' => 'Finanças',
      'category_key' => 'financas',
      'icon' => '🕒',
      'gradient' => 'linear-gradient(135deg,#f0f5ff,#d8e4ff)',
      'excerpt' => 'Ferramenta online para usar Calculadora de Horas de Trabalho com rapidez e praticidade.',
      'lead' => 'Calcule o total de horas trabalhadas usando horário de entrada, saída e intervalo.',
      'keywords' => 'calculadora horas de trabalho, horas trabalhadas online, jornada trabalho',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
        0 => 'calculadora-salario-liquido',
        1 => 'calculadora-roi',
        2 => 'contador-palavras',
      ),
    ),
    'calculadora-idade' => 
    array (
      'slug' => 'calculadora-idade',
      'legacy_file' => 'calculadora-idade.php',
      'page_key' => 'tool:calculadora-idade',
      'name' => 'Calculadora de Idade',
      'short_name' => 'Idade',
      'category' => 'Datas',
      'category_key' => 'datas',
      'icon' => '🎂',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Calculadora de Idade com rapidez e praticidade.',
      'lead' => 'Calculadora de Idade online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'calculadora-idade, ferramenta online, Calculadora de Idade',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'calculadora-imc' => 
    array (
      'slug' => 'calculadora-imc',
      'legacy_file' => 'calculadora-imc.php',
      'page_key' => 'tool:calculadora-imc',
      'name' => 'Calculadora de IMC',
      'short_name' => 'IMC',
      'category' => 'Saúde',
      'category_key' => 'saude',
      'icon' => '⚖️',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Calculadora de IMC com rapidez e praticidade.',
      'lead' => 'Calculadora de IMC online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'calculadora-imc, ferramenta online, Calculadora de IMC',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'calculadora-imposto-renda' => 
    array (
      'slug' => 'calculadora-imposto-renda',
      'legacy_file' => 'calculadora-imposto-renda.php',
      'page_key' => 'tool:calculadora-imposto-renda',
      'name' => 'Calculadora de Imposto de Renda',
      'short_name' => 'Imposto de Renda',
      'category' => 'Finanças',
      'category_key' => 'financas',
      'icon' => '🧾',
      'gradient' => 'linear-gradient(135deg,#eef8ff,#d6ebff)',
      'excerpt' => 'Ferramenta online para usar Calculadora de Imposto de Renda com rapidez e praticidade.',
      'lead' => 'Estime o imposto de renda mensal a partir do salário bruto e das deduções informadas.',
      'keywords' => 'calculadora imposto de renda, irrf online, imposto de renda salário',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
        0 => 'calculadora-inss',
        1 => 'calculadora-salario-liquido',
        2 => 'calculadora-fgts',
      ),
    ),
    'calculadora-inflacao' => 
    array (
      'slug' => 'calculadora-inflacao',
      'legacy_file' => 'calculadora-inflacao.php',
      'page_key' => 'tool:calculadora-inflacao',
      'name' => 'Calculadora de Inflação',
      'short_name' => 'Inflação',
      'category' => 'Finanças',
      'category_key' => 'financas',
      'icon' => '📈',
      'gradient' => 'linear-gradient(135deg,#fff4f1,#ffd7ce)',
      'excerpt' => 'Ferramenta online para usar Calculadora de Inflação com rapidez e praticidade.',
      'lead' => 'Atualize um valor aplicando uma taxa de inflação para estimar perda de poder de compra ou reajuste.',
      'keywords' => 'calculadora inflação, valor corrigido pela inflação, reajuste inflação',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
        0 => 'calculadora-correcao-monetaria',
        1 => 'calculadora-aluguel-reajuste',
        2 => 'calculadora-rendimento-poupanca',
      ),
    ),
    'calculadora-inss' => 
    array (
      'slug' => 'calculadora-inss',
      'legacy_file' => 'calculadora-inss.php',
      'page_key' => 'tool:calculadora-inss',
      'name' => 'Calculadora de INSS',
      'short_name' => 'INSS',
      'category' => 'Finanças',
      'category_key' => 'financas',
      'icon' => '🏛️',
      'gradient' => 'linear-gradient(135deg,#f4f9ff,#dbe9ff)',
      'excerpt' => 'Ferramenta online para usar Calculadora de INSS com rapidez e praticidade.',
      'lead' => 'Calcule uma estimativa de desconto de INSS com base no salário bruto mensal.',
      'keywords' => 'calculadora inss, desconto inss online, inss salário',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
        0 => 'calculadora-imposto-renda',
        1 => 'calculadora-salario-liquido',
        2 => 'calculadora-fgts',
      ),
    ),
    'calculadora-investimento-mensal' => 
    array (
      'slug' => 'calculadora-investimento-mensal',
      'legacy_file' => 'calculadora-investimento-mensal.php',
      'page_key' => 'tool:calculadora-investimento-mensal',
      'name' => 'Calculadora de Investimento Mensal',
      'short_name' => 'Investimento Mensal',
      'category' => 'Finanças',
      'category_key' => 'financas',
      'icon' => '📅',
      'gradient' => 'linear-gradient(135deg,#f1f8ff,#dce8ff)',
      'excerpt' => 'Ferramenta online para usar Calculadora de Investimento Mensal com rapidez e praticidade.',
      'lead' => 'Simule o acúmulo de aportes mensais com rentabilidade e prazo definidos.',
      'keywords' => 'calculadora investimento mensal, aporte mensal, acumular investimento',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
        0 => 'calculadora-cdi',
        1 => 'calculadora-rendimento-poupanca',
        2 => 'juros-compostos',
      ),
    ),
    'calculadora-juros-atraso' => 
    array (
      'slug' => 'calculadora-juros-atraso',
      'legacy_file' => 'calculadora-juros-atraso.php',
      'page_key' => 'tool:calculadora-juros-atraso',
      'name' => 'Calculadora de Juros por Atraso',
      'short_name' => 'Juros por Atraso',
      'category' => 'Finanças',
      'category_key' => 'financas',
      'icon' => '📅',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Calculadora de Juros por Atraso com rapidez e praticidade.',
      'lead' => 'Calculadora de Juros por Atraso online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'calculadora-juros-atraso, ferramenta online, Calculadora de Juros por Atraso',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'calculadora-margem-lucro' => 
    array (
      'slug' => 'calculadora-margem-lucro',
      'legacy_file' => 'calculadora-margem-lucro.php',
      'page_key' => 'tool:calculadora-margem-lucro',
      'name' => 'Calculadora de Margem de Lucro',
      'short_name' => 'Margem de Lucro',
      'category' => 'Finanças',
      'category_key' => 'financas',
      'icon' => '💵',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Calculadora de Margem de Lucro com rapidez e praticidade.',
      'lead' => 'Calculadora de Margem de Lucro online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'calculadora-margem-lucro, ferramenta online, Calculadora de Margem de Lucro',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'calculadora-markup' => 
    array (
      'slug' => 'calculadora-markup',
      'legacy_file' => 'calculadora-markup.php',
      'page_key' => 'tool:calculadora-markup',
      'name' => 'Calculadora de Markup',
      'short_name' => 'Markup',
      'category' => 'Finanças',
      'category_key' => 'financas',
      'icon' => '🧮',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Calculadora de Markup com rapidez e praticidade.',
      'lead' => 'Calculadora de Markup online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'calculadora-markup, ferramenta online, Calculadora de Markup',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'calculadora-media-escolar' => 
    array (
      'slug' => 'calculadora-media-escolar',
      'legacy_file' => 'calculadora-media-escolar.php',
      'page_key' => 'tool:calculadora-media-escolar',
      'name' => 'Calculadora de Média Escolar',
      'short_name' => 'Média Escolar',
      'category' => 'Matemática',
      'category_key' => 'matematica',
      'icon' => '📝',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Calculadora de Média Escolar com rapidez e praticidade.',
      'lead' => 'Calculadora de Média Escolar online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'calculadora-media-escolar, ferramenta online, Calculadora de Média Escolar',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'calculadora-multa-atraso' => 
    array (
      'slug' => 'calculadora-multa-atraso',
      'legacy_file' => 'calculadora-multa-atraso.php',
      'page_key' => 'tool:calculadora-multa-atraso',
      'name' => 'Calculadora de Multa por Atraso',
      'short_name' => 'Multa por Atraso',
      'category' => 'Finanças',
      'category_key' => 'financas',
      'icon' => '⏰',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Calculadora de Multa por Atraso com rapidez e praticidade.',
      'lead' => 'Calculadora de Multa por Atraso online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'calculadora-multa-atraso, ferramenta online, Calculadora de Multa por Atraso',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'calculadora-porcentagem' => 
    array (
      'slug' => 'calculadora-porcentagem',
      'legacy_file' => 'calculadora-porcentagem.php',
      'page_key' => 'tool:calculadora-porcentagem',
      'name' => 'Calculadora de Porcentagem',
      'short_name' => 'Porcentagem',
      'category' => 'Matemática',
      'category_key' => 'matematica',
      'icon' => '%',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Calculadora de Porcentagem com rapidez e praticidade.',
      'lead' => 'Calculadora de Porcentagem online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'calculadora-porcentagem, ferramenta online, Calculadora de Porcentagem',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'calculadora-potencia' => 
    array (
      'slug' => 'calculadora-potencia',
      'legacy_file' => 'calculadora-potencia.php',
      'page_key' => 'tool:calculadora-potencia',
      'name' => 'Calculadora de Potência',
      'short_name' => 'Potência',
      'category' => 'Matemática',
      'category_key' => 'matematica',
      'icon' => 'xʸ',
      'gradient' => 'linear-gradient(135deg,#f7f3ff,#e3d9ff)',
      'excerpt' => 'Ferramenta online para usar Calculadora de Potência com rapidez e praticidade.',
      'lead' => 'Eleve uma base a um expoente com cálculo rápido e resposta imediata no navegador.',
      'keywords' => 'calculadora de potência, potência online, elevar número',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
        0 => 'calculadora-raiz-quadrada',
        1 => 'calculadora-area-quadrado',
        2 => 'calculadora-regra-de-tres',
      ),
    ),
    'calculadora-raiz-quadrada' => 
    array (
      'slug' => 'calculadora-raiz-quadrada',
      'legacy_file' => 'calculadora-raiz-quadrada.php',
      'page_key' => 'tool:calculadora-raiz-quadrada',
      'name' => 'Calculadora de Raiz Quadrada',
      'short_name' => 'Raiz Quadrada',
      'category' => 'Matemática',
      'category_key' => 'matematica',
      'icon' => '√',
      'gradient' => 'linear-gradient(135deg,#eefaf7,#d9f4ea)',
      'excerpt' => 'Ferramenta online para usar Calculadora de Raiz Quadrada com rapidez e praticidade.',
      'lead' => 'Calcule a raiz quadrada de um número com resposta imediata e interpretação simples.',
      'keywords' => 'calculadora raiz quadrada, raiz quadrada online, calcular raiz',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
        0 => 'calculadora-potencia',
        1 => 'calculadora-porcentagem',
        2 => 'calculadora-regra-de-tres',
      ),
    ),
    'calculadora-regra-de-tres' => 
    array (
      'slug' => 'calculadora-regra-de-tres',
      'legacy_file' => 'calculadora-regra-de-tres.php',
      'page_key' => 'tool:calculadora-regra-de-tres',
      'name' => 'Calculadora de Regra de Três',
      'short_name' => 'Regra de Três',
      'category' => 'Matemática',
      'category_key' => 'matematica',
      'icon' => '📐',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Calculadora de Regra de Três com rapidez e praticidade.',
      'lead' => 'Calculadora de Regra de Três online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'calculadora-regra-de-tres, ferramenta online, Calculadora de Regra de Três',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'calculadora-rendimento-poupanca' => 
    array (
      'slug' => 'calculadora-rendimento-poupanca',
      'legacy_file' => 'calculadora-rendimento-poupanca.php',
      'page_key' => 'tool:calculadora-rendimento-poupanca',
      'name' => 'Calculadora de Rendimento da Poupança',
      'short_name' => 'Rendimento da Poupança',
      'category' => 'Finanças',
      'category_key' => 'financas',
      'icon' => '🏦',
      'gradient' => 'linear-gradient(135deg,#eef8f0,#d7efdb)',
      'excerpt' => 'Ferramenta online para usar Calculadora de Rendimento da Poupança com rapidez e praticidade.',
      'lead' => 'Simule o rendimento da poupança usando valor investido, taxa mensal e prazo da aplicação.',
      'keywords' => 'calculadora rendimento poupança, poupança online, simulação poupança',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
        0 => 'calculadora-cdi',
        1 => 'calculadora-investimento-mensal',
        2 => 'juros-compostos',
      ),
    ),
    'calculadora-roi' => 
    array (
      'slug' => 'calculadora-roi',
      'legacy_file' => 'calculadora-roi.php',
      'page_key' => 'tool:calculadora-roi',
      'name' => 'Calculadora de ROI',
      'short_name' => 'ROI',
      'category' => 'Finanças',
      'category_key' => 'financas',
      'icon' => '📈',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Calculadora de ROI com rapidez e praticidade.',
      'lead' => 'Calculadora de ROI online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'calculadora-roi, ferramenta online, Calculadora de ROI',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'calculadora-salario-liquido' => 
    array (
      'slug' => 'calculadora-salario-liquido',
      'legacy_file' => 'calculadora-salario-liquido.php',
      'page_key' => 'tool:calculadora-salario-liquido',
      'name' => 'Calculadora de Salário Líquido',
      'short_name' => 'Salário Líquido',
      'category' => 'Finanças',
      'category_key' => 'financas',
      'icon' => '💼',
      'gradient' => 'linear-gradient(135deg,#eef9f2,#d8f0e0)',
      'excerpt' => 'Ferramenta online para usar Calculadora de Salário Líquido com rapidez e praticidade.',
      'lead' => 'Estime o salário líquido usando salário bruto, INSS, imposto e desconto adicional.',
      'keywords' => 'calculadora salário líquido, salário líquido online, desconto salário',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
        0 => 'calculadora-imposto-renda',
        1 => 'calculadora-inss',
        2 => 'calculadora-fgts',
      ),
    ),
    'calculadora-taxa-crescimento' => 
    array (
      'slug' => 'calculadora-taxa-crescimento',
      'legacy_file' => 'calculadora-taxa-crescimento.php',
      'page_key' => 'tool:calculadora-taxa-crescimento',
      'name' => 'Calculadora de Taxa de Crescimento',
      'short_name' => 'Taxa de Crescimento',
      'category' => 'Finanças',
      'category_key' => 'financas',
      'icon' => '🌱',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Calculadora de Taxa de Crescimento com rapidez e praticidade.',
      'lead' => 'Calculadora de Taxa de Crescimento online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'calculadora-taxa-crescimento, ferramenta online, Calculadora de Taxa de Crescimento',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'calculadora-tempo-viagem' => 
    array (
      'slug' => 'calculadora-tempo-viagem',
      'legacy_file' => 'calculadora-tempo-viagem.php',
      'page_key' => 'tool:calculadora-tempo-viagem',
      'name' => 'Calculadora de Tempo de Viagem',
      'short_name' => 'Tempo de Viagem',
      'category' => 'Matemática',
      'category_key' => 'matematica',
      'icon' => '🛣️',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Calculadora de Tempo de Viagem com rapidez e praticidade.',
      'lead' => 'Calculadora de Tempo de Viagem online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'calculadora-tempo-viagem, ferramenta online, Calculadora de Tempo de Viagem',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'calculadora-velocidade-media' => 
    array (
      'slug' => 'calculadora-velocidade-media',
      'legacy_file' => 'calculadora-velocidade-media.php',
      'page_key' => 'tool:calculadora-velocidade-media',
      'name' => 'Calculadora de Velocidade Média',
      'short_name' => 'Velocidade Média',
      'category' => 'Matemática',
      'category_key' => 'matematica',
      'icon' => '🚗',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Calculadora de Velocidade Média com rapidez e praticidade.',
      'lead' => 'Calculadora de Velocidade Média online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'calculadora-velocidade-media, ferramenta online, Calculadora de Velocidade Média',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'calculadora-volume-cilindro' => 
    array (
      'slug' => 'calculadora-volume-cilindro',
      'legacy_file' => 'calculadora-volume-cilindro.php',
      'page_key' => 'tool:calculadora-volume-cilindro',
      'name' => 'Calculadora de Volume do Cilindro',
      'short_name' => 'Volume do Cilindro',
      'category' => 'Matemática',
      'category_key' => 'matematica',
      'icon' => '🥫',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Calculadora de Volume do Cilindro com rapidez e praticidade.',
      'lead' => 'Calculadora de Volume do Cilindro online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'calculadora-volume-cilindro, ferramenta online, Calculadora de Volume do Cilindro',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'calculadora-volume-esfera' => 
    array (
      'slug' => 'calculadora-volume-esfera',
      'legacy_file' => 'calculadora-volume-esfera.php',
      'page_key' => 'tool:calculadora-volume-esfera',
      'name' => 'Calculadora de Volume da Esfera',
      'short_name' => 'Volume da Esfera',
      'category' => 'Matemática',
      'category_key' => 'matematica',
      'icon' => '⚽',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Calculadora de Volume da Esfera com rapidez e praticidade.',
      'lead' => 'Calculadora de Volume da Esfera online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'calculadora-volume-esfera, ferramenta online, Calculadora de Volume da Esfera',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'capitalizar-texto' => 
    array (
      'slug' => 'capitalizar-texto',
      'legacy_file' => 'capitalizar-texto.php',
      'page_key' => 'tool:capitalizar-texto',
      'name' => 'Capitalizar Texto',
      'short_name' => 'Capitalizar Texto',
      'category' => 'Texto e Produtividade',
      'category_key' => 'texto',
      'icon' => '✍️',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Capitalizar Texto com rapidez e praticidade.',
      'lead' => 'Capitalizar Texto online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'capitalizar-texto, ferramenta online, Capitalizar Texto',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'comparador-texto' => 
    array (
      'slug' => 'comparador-texto',
      'legacy_file' => 'comparador-texto.php',
      'page_key' => 'tool:comparador-texto',
      'name' => 'Comparador de Texto',
      'short_name' => 'Comparador de Texto',
      'category' => 'Texto e Produtividade',
      'category_key' => 'texto',
      'icon' => '🆚',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Comparador de Texto com rapidez e praticidade.',
      'lead' => 'Comparador de Texto online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'comparador-texto, ferramenta online, Comparador de Texto',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'contador-caracteres' => 
    array (
      'slug' => 'contador-caracteres',
      'legacy_file' => 'contador-caracteres.php',
      'page_key' => 'tool:contador-caracteres',
      'name' => 'Contador de Caracteres',
      'short_name' => 'Caracteres',
      'category' => 'Texto e Produtividade',
      'category_key' => 'texto',
      'icon' => '🔢',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Contador de Caracteres com rapidez e praticidade.',
      'lead' => 'Contador de Caracteres online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'contador-caracteres, ferramenta online, Contador de Caracteres',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'contador-caracteres-twitter' => 
    array (
      'slug' => 'contador-caracteres-twitter',
      'legacy_file' => 'contador-caracteres-twitter.php',
      'page_key' => 'tool:contador-caracteres-twitter',
      'name' => 'Contador de Caracteres para Twitter',
      'short_name' => 'Caracteres para Twitter',
      'category' => 'Texto e Produtividade',
      'category_key' => 'texto',
      'icon' => '🐦',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Contador de Caracteres para Twitter com rapidez e praticidade.',
      'lead' => 'Contador de Caracteres para Twitter online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'contador-caracteres-twitter, ferramenta online, Contador de Caracteres para Twitter',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'contador-linhas-codigo' => 
    array (
      'slug' => 'contador-linhas-codigo',
      'legacy_file' => 'contador-linhas-codigo.php',
      'page_key' => 'tool:contador-linhas-codigo',
      'name' => 'Contador de Linhas de Código',
      'short_name' => 'Linhas de Código',
      'category' => 'Desenvolvimento',
      'category_key' => 'desenvolvimento',
      'icon' => '📏',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Contador de Linhas de Código com rapidez e praticidade.',
      'lead' => 'Contador de Linhas de Código online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'contador-linhas-codigo, ferramenta online, Contador de Linhas de Código',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'contador-palavras' => 
    array (
      'slug' => 'contador-palavras',
      'legacy_file' => 'contador-palavras.php',
      'page_key' => 'tool:contador-palavras',
      'name' => 'Contador de Palavras',
      'short_name' => 'Palavras',
      'category' => 'Texto e Produtividade',
      'category_key' => 'texto',
      'icon' => '📄',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Contador de Palavras com rapidez e praticidade.',
      'lead' => 'Contador de Palavras online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'contador-palavras, ferramenta online, Contador de Palavras',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'contador-palavras-seo' => 
    array (
      'slug' => 'contador-palavras-seo',
      'legacy_file' => 'contador-palavras-seo.php',
      'page_key' => 'tool:contador-palavras-seo',
      'name' => 'Contador de Palavras SEO',
      'short_name' => 'Palavras SEO',
      'category' => 'SEO',
      'category_key' => 'seo',
      'icon' => '📝',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Contador de Palavras SEO com rapidez e praticidade.',
      'lead' => 'Contador de Palavras SEO online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'contador-palavras-seo, ferramenta online, Contador de Palavras SEO',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'conversor-anos-dias' => 
    array (
      'slug' => 'conversor-anos-dias',
      'legacy_file' => 'conversor-anos-dias.php',
      'page_key' => 'tool:conversor-anos-dias',
      'name' => 'Conversor de Anos para Dias',
      'short_name' => 'Anos para Dias',
      'category' => 'Conversão',
      'category_key' => 'conversao',
      'icon' => '📆',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Conversor de Anos para Dias com rapidez e praticidade.',
      'lead' => 'Conversor de Anos para Dias online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'conversor-anos-dias, ferramenta online, Conversor de Anos para Dias',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'conversor-bytes' => 
    array (
      'slug' => 'conversor-bytes',
      'legacy_file' => 'conversor-bytes.php',
      'page_key' => 'tool:conversor-bytes',
      'name' => 'Conversor de Bytes',
      'short_name' => 'Bytes',
      'category' => 'Conversão',
      'category_key' => 'conversao',
      'icon' => '💾',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Conversor de Bytes com rapidez e praticidade.',
      'lead' => 'Conversor de Bytes online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'conversor-bytes, ferramenta online, Conversor de Bytes',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'conversor-horas-minutos' => 
    array (
      'slug' => 'conversor-horas-minutos',
      'legacy_file' => 'conversor-horas-minutos.php',
      'page_key' => 'tool:conversor-horas-minutos',
      'name' => 'Conversor de Horas para Minutos',
      'short_name' => 'Horas para Minutos',
      'category' => 'Conversão',
      'category_key' => 'conversao',
      'icon' => '⏱️',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Conversor de Horas para Minutos com rapidez e praticidade.',
      'lead' => 'Conversor de Horas para Minutos online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'conversor-horas-minutos, ferramenta online, Conversor de Horas para Minutos',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'conversor-km-milhas' => 
    array (
      'slug' => 'conversor-km-milhas',
      'legacy_file' => 'conversor-km-milhas.php',
      'page_key' => 'tool:conversor-km-milhas',
      'name' => 'Conversor de Km para Milhas',
      'short_name' => 'Km para Milhas',
      'category' => 'Conversão',
      'category_key' => 'conversao',
      'icon' => '🛣️',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Conversor de Km para Milhas com rapidez e praticidade.',
      'lead' => 'Conversor de Km para Milhas online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'conversor-km-milhas, ferramenta online, Conversor de Km para Milhas',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'conversor-segundos-horas' => 
    array (
      'slug' => 'conversor-segundos-horas',
      'legacy_file' => 'conversor-segundos-horas.php',
      'page_key' => 'tool:conversor-segundos-horas',
      'name' => 'Conversor de Segundos para Horas',
      'short_name' => 'Segundos para Horas',
      'category' => 'Conversão',
      'category_key' => 'conversao',
      'icon' => '⌛',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Conversor de Segundos para Horas com rapidez e praticidade.',
      'lead' => 'Conversor de Segundos para Horas online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'conversor-segundos-horas, ferramenta online, Conversor de Segundos para Horas',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'conversor-temperatura' => 
    array (
      'slug' => 'conversor-temperatura',
      'legacy_file' => 'conversor-temperatura.php',
      'page_key' => 'tool:conversor-temperatura',
      'name' => 'Conversor de Temperatura',
      'short_name' => 'Temperatura',
      'category' => 'Conversão',
      'category_key' => 'conversao',
      'icon' => '🌡️',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Conversor de Temperatura com rapidez e praticidade.',
      'lead' => 'Conversor de Temperatura online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'conversor-temperatura, ferramenta online, Conversor de Temperatura',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'conversor-texto' => 
    array (
      'slug' => 'conversor-texto',
      'legacy_file' => 'conversor-texto.php',
      'page_key' => 'tool:conversor-texto',
      'name' => 'Conversor de Texto',
      'short_name' => 'Texto',
      'category' => 'Texto e Produtividade',
      'category_key' => 'texto',
      'icon' => '🔄',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Conversor de Texto com rapidez e praticidade.',
      'lead' => 'Conversor de Texto online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'conversor-texto, ferramenta online, Conversor de Texto',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'decoder-base64' => 
    array (
      'slug' => 'decoder-base64',
      'legacy_file' => 'decoder-base64.php',
      'page_key' => 'tool:decoder-base64',
      'name' => 'Decoder Base64',
      'short_name' => 'Decoder Base64',
      'category' => 'Desenvolvimento',
      'category_key' => 'desenvolvimento',
      'icon' => '🔓',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Decoder Base64 com rapidez e praticidade.',
      'lead' => 'Decoder Base64 online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'decoder-base64, ferramenta online, Decoder Base64',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'decoder-html' => 
    array (
      'slug' => 'decoder-html',
      'legacy_file' => 'decoder-html.php',
      'page_key' => 'tool:decoder-html',
      'name' => 'Decoder HTML',
      'short_name' => 'Decoder HTML',
      'category' => 'Desenvolvimento',
      'category_key' => 'desenvolvimento',
      'icon' => '🧾',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Decoder HTML com rapidez e praticidade.',
      'lead' => 'Decoder HTML online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'decoder-html, ferramenta online, Decoder HTML',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'decoder-url' => 
    array (
      'slug' => 'decoder-url',
      'legacy_file' => 'decoder-url.php',
      'page_key' => 'tool:decoder-url',
      'name' => 'Decoder URL',
      'short_name' => 'Decoder URL',
      'category' => 'Desenvolvimento',
      'category_key' => 'desenvolvimento',
      'icon' => '🔍',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Decoder URL com rapidez e praticidade.',
      'lead' => 'Decoder URL online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'decoder-url, ferramenta online, Decoder URL',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'densidade-palavra-chave' => 
    array (
      'slug' => 'densidade-palavra-chave',
      'legacy_file' => 'densidade-palavra-chave.php',
      'page_key' => 'tool:densidade-palavra-chave',
      'name' => 'Densidade de Palavra-Chave',
      'short_name' => 'Densidade de Palavra-Chave',
      'category' => 'SEO',
      'category_key' => 'seo',
      'icon' => '🔑',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Densidade de Palavra-Chave com rapidez e praticidade.',
      'lead' => 'Densidade de Palavra-Chave online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'densidade-palavra-chave, ferramenta online, Densidade de Palavra-Chave',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'encoder-base64' => 
    array (
      'slug' => 'encoder-base64',
      'legacy_file' => 'encoder-base64.php',
      'page_key' => 'tool:encoder-base64',
      'name' => 'Encoder Base64',
      'short_name' => 'Encoder Base64',
      'category' => 'Desenvolvimento',
      'category_key' => 'desenvolvimento',
      'icon' => '🔐',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Encoder Base64 com rapidez e praticidade.',
      'lead' => 'Encoder Base64 online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'encoder-base64, ferramenta online, Encoder Base64',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'encoder-html' => 
    array (
      'slug' => 'encoder-html',
      'legacy_file' => 'encoder-html.php',
      'page_key' => 'tool:encoder-html',
      'name' => 'Encoder HTML',
      'short_name' => 'Encoder HTML',
      'category' => 'Desenvolvimento',
      'category_key' => 'desenvolvimento',
      'icon' => '🏷',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Encoder HTML com rapidez e praticidade.',
      'lead' => 'Encoder HTML online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'encoder-html, ferramenta online, Encoder HTML',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'encoder-url' => 
    array (
      'slug' => 'encoder-url',
      'legacy_file' => 'encoder-url.php',
      'page_key' => 'tool:encoder-url',
      'name' => 'Encoder URL',
      'short_name' => 'Encoder URL',
      'category' => 'Desenvolvimento',
      'category_key' => 'desenvolvimento',
      'icon' => '🌐',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Encoder URL com rapidez e praticidade.',
      'lead' => 'Encoder URL online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'encoder-url, ferramenta online, Encoder URL',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'formatador-json' => 
    array (
      'slug' => 'formatador-json',
      'legacy_file' => 'formatador-json.php',
      'page_key' => 'tool:formatador-json',
      'name' => 'Formatador JSON',
      'short_name' => 'Formatador JSON',
      'category' => 'Desenvolvimento',
      'category_key' => 'desenvolvimento',
      'icon' => '🧩',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Formatador JSON com rapidez e praticidade.',
      'lead' => 'Formatador JSON online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'formatador-json, ferramenta online, Formatador JSON',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'gerador-breadcrumb-schema' => 
    array (
      'slug' => 'gerador-breadcrumb-schema',
      'legacy_file' => 'gerador-breadcrumb-schema.php',
      'page_key' => 'tool:gerador-breadcrumb-schema',
      'name' => 'Gerador de Breadcrumb Schema',
      'short_name' => 'Breadcrumb Schema',
      'category' => 'SEO',
      'category_key' => 'seo',
      'icon' => '🧭',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Gerador de Breadcrumb Schema com rapidez e praticidade.',
      'lead' => 'Gerador de Breadcrumb Schema online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'gerador-breadcrumb-schema, ferramenta online, Gerador de Breadcrumb Schema',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'gerador-cpf' => 
    array (
      'slug' => 'gerador-cpf',
      'legacy_file' => 'gerador-cpf.php',
      'page_key' => 'tool:gerador-cpf',
      'name' => 'Gerador de CPF',
      'short_name' => 'CPF',
      'category' => 'Geradores',
      'category_key' => 'geradores',
      'icon' => '🪪',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Gerador de CPF com rapidez e praticidade.',
      'lead' => 'Gerador de CPF online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'gerador-cpf, ferramenta online, Gerador de CPF',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'gerador-faq-schema' => 
    array (
      'slug' => 'gerador-faq-schema',
      'legacy_file' => 'gerador-faq-schema.php',
      'page_key' => 'tool:gerador-faq-schema',
      'name' => 'Gerador de FAQ Schema',
      'short_name' => 'FAQ Schema',
      'category' => 'SEO',
      'category_key' => 'seo',
      'icon' => '❓',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Gerador de FAQ Schema com rapidez e praticidade.',
      'lead' => 'Gerador de FAQ Schema online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'gerador-faq-schema, ferramenta online, Gerador de FAQ Schema',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'gerador-hash-sha256' => 
    array (
      'slug' => 'gerador-hash-sha256',
      'legacy_file' => 'gerador-hash-sha256.php',
      'page_key' => 'tool:gerador-hash-sha256',
      'name' => 'Gerador de Hash SHA256',
      'short_name' => 'Hash SHA256',
      'category' => 'Desenvolvimento',
      'category_key' => 'desenvolvimento',
      'icon' => '🔒',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Gerador de Hash SHA256 com rapidez e praticidade.',
      'lead' => 'Gerador de Hash SHA256 online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'gerador-hash-sha256, ferramenta online, Gerador de Hash SHA256',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'gerador-meta-tags' => 
    array (
      'slug' => 'gerador-meta-tags',
      'legacy_file' => 'gerador-meta-tags.php',
      'page_key' => 'tool:gerador-meta-tags',
      'name' => 'Gerador de Meta Tags',
      'short_name' => 'Meta Tags',
      'category' => 'SEO',
      'category_key' => 'seo',
      'icon' => '🏷️',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Gerador de Meta Tags com rapidez e praticidade.',
      'lead' => 'Gerador de Meta Tags online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'gerador-meta-tags, ferramenta online, Gerador de Meta Tags',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'gerador-nomes' => 
    array (
      'slug' => 'gerador-nomes',
      'legacy_file' => 'gerador-nomes.php',
      'page_key' => 'tool:gerador-nomes',
      'name' => 'Gerador de Nomes',
      'short_name' => 'Nomes',
      'category' => 'Geradores',
      'category_key' => 'geradores',
      'icon' => '👤',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Gerador de Nomes com rapidez e praticidade.',
      'lead' => 'Gerador de Nomes online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'gerador-nomes, ferramenta online, Gerador de Nomes',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'gerador-robots-txt' => 
    array (
      'slug' => 'gerador-robots-txt',
      'legacy_file' => 'gerador-robots-txt.php',
      'page_key' => 'tool:gerador-robots-txt',
      'name' => 'Gerador de Robots.txt',
      'short_name' => 'Robots.txt',
      'category' => 'SEO',
      'category_key' => 'seo',
      'icon' => '🤖',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Gerador de Robots.txt com rapidez e praticidade.',
      'lead' => 'Gerador de Robots.txt online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'gerador-robots-txt, ferramenta online, Gerador de Robots.txt',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'gerador-senhas' => 
    array (
      'slug' => 'gerador-senhas',
      'legacy_file' => 'gerador-senhas.php',
      'page_key' => 'tool:gerador-senhas',
      'name' => 'Gerador de Senhas',
      'short_name' => 'Senhas',
      'category' => 'Geradores',
      'category_key' => 'geradores',
      'icon' => '🔐',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Gerador de Senhas com rapidez e praticidade.',
      'lead' => 'Gerador de Senhas online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'gerador-senhas, ferramenta online, Gerador de Senhas',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'gerador-slug-url' => 
    array (
      'slug' => 'gerador-slug-url',
      'legacy_file' => 'gerador-slug-url.php',
      'page_key' => 'tool:gerador-slug-url',
      'name' => 'Gerador de Slug URL',
      'short_name' => 'Slug URL',
      'category' => 'Desenvolvimento',
      'category_key' => 'desenvolvimento',
      'icon' => '🔗',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Gerador de Slug URL com rapidez e praticidade.',
      'lead' => 'Gerador de Slug URL online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'gerador-slug-url, ferramenta online, Gerador de Slug URL',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'gerador-uuid' => 
    array (
      'slug' => 'gerador-uuid',
      'legacy_file' => 'gerador-uuid.php',
      'page_key' => 'tool:gerador-uuid',
      'name' => 'Gerador de UUID',
      'short_name' => 'UUID',
      'category' => 'Desenvolvimento',
      'category_key' => 'desenvolvimento',
      'icon' => '🆔',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Gerador de UUID com rapidez e praticidade.',
      'lead' => 'Gerador de UUID online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'gerador-uuid, ferramenta online, Gerador de UUID',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'inverter-texto' => 
    array (
      'slug' => 'inverter-texto',
      'legacy_file' => 'inverter-texto.php',
      'page_key' => 'tool:inverter-texto',
      'name' => 'Inverter Texto',
      'short_name' => 'Inverter Texto',
      'category' => 'Texto e Produtividade',
      'category_key' => 'texto',
      'icon' => '🔁',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Inverter Texto com rapidez e praticidade.',
      'lead' => 'Inverter Texto online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'inverter-texto, ferramenta online, Inverter Texto',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'juros-compostos' => 
    array (
      'slug' => 'juros-compostos',
      'legacy_file' => 'juros-compostos.php',
      'page_key' => 'tool:juros-compostos',
      'name' => 'Calculadora de Juros Compostos',
      'short_name' => 'Juros Compostos',
      'category' => 'Finanças',
      'category_key' => 'financas',
      'icon' => '📈',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Calculadora de Juros Compostos com rapidez e praticidade.',
      'lead' => 'Calculadora de Juros Compostos online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'juros-compostos, ferramenta online, Calculadora de Juros Compostos',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'juros-simples' => 
    array (
      'slug' => 'juros-simples',
      'legacy_file' => 'juros-simples.php',
      'page_key' => 'tool:juros-simples',
      'name' => 'Calculadora de Juros Simples',
      'short_name' => 'Juros Simples',
      'category' => 'Finanças',
      'category_key' => 'financas',
      'icon' => '💰',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Calculadora de Juros Simples com rapidez e praticidade.',
      'lead' => 'Calculadora de Juros Simples online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'juros-simples, ferramenta online, Calculadora de Juros Simples',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'remover-espacos-extras' => 
    array (
      'slug' => 'remover-espacos-extras',
      'legacy_file' => 'remover-espacos-extras.php',
      'page_key' => 'tool:remover-espacos-extras',
      'name' => 'Remover Espaços Extras',
      'short_name' => 'Remover Espaços Extras',
      'category' => 'Texto e Produtividade',
      'category_key' => 'texto',
      'icon' => '✂️',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Remover Espaços Extras com rapidez e praticidade.',
      'lead' => 'Remover Espaços Extras online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'remover-espacos-extras, ferramenta online, Remover Espaços Extras',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'simulador-financiamento' => 
    array (
      'slug' => 'simulador-financiamento',
      'legacy_file' => 'simulador-financiamento.php',
      'page_key' => 'tool:simulador-financiamento',
      'name' => 'Simulador de Financiamento',
      'short_name' => 'Financiamento',
      'category' => 'Finanças',
      'category_key' => 'financas',
      'icon' => '🏠',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Simulador de Financiamento com rapidez e praticidade.',
      'lead' => 'Simulador de Financiamento online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'simulador-financiamento, ferramenta online, Simulador de Financiamento',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'texto-maiusculo' => 
    array (
      'slug' => 'texto-maiusculo',
      'legacy_file' => 'texto-maiusculo.php',
      'page_key' => 'tool:texto-maiusculo',
      'name' => 'Texto Maiúsculo',
      'short_name' => 'Texto Maiúsculo',
      'category' => 'Texto e Produtividade',
      'category_key' => 'texto',
      'icon' => '🔠',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Texto Maiúsculo com rapidez e praticidade.',
      'lead' => 'Texto Maiúsculo online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'texto-maiusculo, ferramenta online, Texto Maiúsculo',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'texto-minusculo' => 
    array (
      'slug' => 'texto-minusculo',
      'legacy_file' => 'texto-minusculo.php',
      'page_key' => 'tool:texto-minusculo',
      'name' => 'Texto Minúsculo',
      'short_name' => 'Texto Minúsculo',
      'category' => 'Texto e Produtividade',
      'category_key' => 'texto',
      'icon' => '🔡',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Texto Minúsculo com rapidez e praticidade.',
      'lead' => 'Texto Minúsculo online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'texto-minusculo, ferramenta online, Texto Minúsculo',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'validador-email' => 
    array (
      'slug' => 'validador-email',
      'legacy_file' => 'validador-email.php',
      'page_key' => 'tool:validador-email',
      'name' => 'Validador de Email',
      'short_name' => 'Validador de Email',
      'category' => 'Desenvolvimento',
      'category_key' => 'desenvolvimento',
      'icon' => '📧',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Validador de Email com rapidez e praticidade.',
      'lead' => 'Validador de Email online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'validador-email, ferramenta online, Validador de Email',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'validador-json' => 
    array (
      'slug' => 'validador-json',
      'legacy_file' => 'validador-json.php',
      'page_key' => 'tool:validador-json',
      'name' => 'Validador JSON',
      'short_name' => 'Validador JSON',
      'category' => 'Desenvolvimento',
      'category_key' => 'desenvolvimento',
      'icon' => '✅',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Validador JSON com rapidez e praticidade.',
      'lead' => 'Validador JSON online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'validador-json, ferramenta online, Validador JSON',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
    'verificador-tamanho-titulo' => 
    array (
      'slug' => 'verificador-tamanho-titulo',
      'legacy_file' => 'verificador-tamanho-titulo.php',
      'page_key' => 'tool:verificador-tamanho-titulo',
      'name' => 'Verificador de Tamanho de Título',
      'short_name' => 'Verificador de Tamanho de Título',
      'category' => 'SEO',
      'category_key' => 'seo',
      'icon' => '📣',
      'gradient' => 'linear-gradient(135deg,#eef4ff,#dbe7ff)',
      'excerpt' => 'Ferramenta online para usar Verificador de Tamanho de Título com rapidez e praticidade.',
      'lead' => 'Verificador de Tamanho de Título online grátis com resposta imediata, interface simples e uso direto no navegador.',
      'keywords' => 'verificador-tamanho-titulo, ferramenta online, Verificador de Tamanho de Título',
      'schema_type' => 'WebApplication',
      'priority' => '0.8',
      'changefreq' => 'monthly',
      'related' => 
      array (
      ),
    ),
  ),
  'categories' => 
  array (
    'desenvolvimento' => 
    array (
      'label' => 'Desenvolvimento',
      'icon' => '🧾',
    ),
    'geradores' => 
    array (
      'label' => 'Geradores',
      'icon' => '🪪',
    ),
    'datas' => 
    array (
      'label' => 'Datas',
      'icon' => '🎂',
    ),
    'financas' => 
    array (
      'label' => 'Finanças',
      'icon' => '📊',
    ),
    'saude' => 
    array (
      'label' => 'Saúde',
      'icon' => '⚖️',
    ),
    'conversao' => 
    array (
      'label' => 'Conversão',
      'icon' => '📆',
    ),
    'texto' => 
    array (
      'label' => 'Texto e Produtividade',
      'icon' => '🔄',
    ),
    'seo' => 
    array (
      'label' => 'SEO',
      'icon' => '🧭',
    ),
    'matematica' => 
    array (
      'label' => 'Matemática',
      'icon' => '🛣️',
    ),
  ),
);
