<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/config/bootstrap.php';
ns_redirect_legacy_url('/ferramentas/calculadora-investimento-mensal');
ns_render_page_start('tool:calculadora-investimento-mensal');
?>
<main><div class="tool-page">
  <nav class="breadcrumb" aria-label="Navegação breadcrumb"><a href="<?= ns_escape(ns_href('/')) ?>">Início</a><span class="sep">›</span><a href="<?= ns_escape(ns_href('/ferramentas')) ?>">Ferramentas</a><span class="sep">›</span><span>Calculadora de Investimento Mensal</span></nav>
  <?php ns_render_ad_slot('leaderboard'); ?>
  <div class="tool-header"><div class="tool-page-icon" style="background:linear-gradient(135deg,#f1f8ff,#dce8ff);">📅</div><div><h1>Calculadora de Investimento Mensal</h1><p>Simule o acúmulo de aportes mensais com rentabilidade e prazo definidos.</p><span class="tag tag-green">Finanças</span></div></div>
  <div class="tool-box">
    <div class="form-row"><div class="form-group"><label for="inv-aporte">Aporte mensal (R$)</label><input type="number" id="inv-aporte" class="form-control" min="0" step="0.01" placeholder="Ex: 500" /></div><div class="form-group"><label for="inv-taxa">Rentabilidade mensal (%)</label><input type="number" id="inv-taxa" class="form-control" min="0" step="0.01" placeholder="Ex: 0.8" /></div><div class="form-group"><label for="inv-meses">Período em meses</label><input type="number" id="inv-meses" class="form-control" min="1" step="1" placeholder="Ex: 36" /></div></div>
    <div class="form-row"><button type="button" class="btn btn-primary" onclick="runTool()">Calcular investimento</button><button type="button" class="btn btn-outline" onclick="clearTool()">Limpar</button><button type="button" class="copy-btn" onclick="copyTool(this)">Copiar resultado</button></div>
    <div class="notice notice-warn" id="tool-error" style="display:none;"><span>⚠️</span><span id="tool-error-text"></span></div>
    <div class="result-box" id="tool-result"><div class="result-label">Resultado do investimento</div><div class="result-grid"><div class="result-item"><div class="label">Valor acumulado</div><div class="value" id="inv-total">-</div></div><div class="result-item"><div class="label">Total investido</div><div class="value" id="inv-aplicado">-</div></div></div><div id="tool-detail" style="margin-top:1rem;color:var(--text2);"></div></div>
  </div>
  <?php ns_render_ad_slot('rectangle'); ?>
<div class="seo-content"><h2>O que é essa ferramenta</h2><p>A calculadora de investimento mensal ajuda a simular quanto um conjunto de aportes periódicos pode acumular ao longo do tempo. Ela é útil para metas financeiras, reserva e planejamento patrimonial.</p><p>O cálculo roda em JavaScript puro no navegador, o que ajuda a manter a página rápida, leve e fácil de usar em qualquer dispositivo. A estrutura também foi pensada para SEO, com conteúdo explicativo, headings claros e foco em intenção de busca real.</p><h2>Como usar</h2><p>Informe o valor do aporte mensal, a rentabilidade esperada por mês e o número de meses. A ferramenta projeta o valor acumulado e mostra quanto foi efetivamente aportado no período.</p><p>Se algum campo estiver vazio ou com valor inválido, a ferramenta mostra uma mensagem amigável antes de liberar o resultado. Depois, você pode copiar a resposta ou limpar tudo para uma nova simulação.</p><h2>Exemplo de uso</h2><p>Se uma pessoa investe R$ 500 por mês por 36 meses com uma rentabilidade mensal estimada, a ferramenta mostra o saldo projetado e permite comparar diferentes cenários.</p><p>Esse contexto adicional torna a página mais útil para visitantes que chegam pela busca orgânica e precisam de uma resposta prática, mas também querem entender como aplicar o resultado.</p><h2>Perguntas frequentes</h2><h3>Serve para metas de longo prazo?</h3><p>Sim. É muito útil para projeções e planejamento progressivo.</p><h3>O cálculo considera aporte mensal no mesmo valor?</h3><p>Sim. Nesta versão o aporte foi padronizado para um valor fixo mensal.</p><h3>Posso comparar com poupança e CDI?</h3><p>Sim. A ferramenta é útil para simular e comparar cenários.</p></div>
  <div class="related-tools"><h2>Ferramentas relacionadas</h2><div class="related-grid"><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-cdi')) ?>" class="related-card"><span class="related-card-icon">💹</span> CDI</a><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-rendimento-poupanca')) ?>" class="related-card"><span class="related-card-icon">🏦</span> Rendimento da Poupança</a><a href="<?= ns_escape(ns_href('/ferramentas/juros-compostos')) ?>" class="related-card"><span class="related-card-icon">📈</span> Juros Compostos</a></div></div>
</div></main>
<script>
function showError(message){document.getElementById('tool-error-text').textContent=message;document.getElementById('tool-error').style.display='flex';document.getElementById('tool-result').classList.remove('show');}
function clearError(){document.getElementById('tool-error').style.display='none';}
function runTool(){const aporte=parseFloat(document.getElementById('inv-aporte').value);const taxa=parseFloat(document.getElementById('inv-taxa').value)/100;const meses=parseInt(document.getElementById('inv-meses').value,10);clearError();if(isNaN(aporte)||isNaN(taxa)||isNaN(meses)||aporte<0||taxa<0||meses<=0){showError('Preencha aporte, taxa e prazo com valores válidos.');return;}let saldo=0;for(let i=0;i<meses;i++){saldo=(saldo+aporte)*(1+taxa);}document.getElementById('inv-total').textContent='R$ '+fmtBRL(saldo);document.getElementById('inv-aplicado').textContent='R$ '+fmtBRL(aporte*meses);document.getElementById('tool-detail').textContent='Simulação com aporte fixo e rentabilidade mensal constante.';showResult('tool-result');}function clearTool(){['inv-aporte','inv-taxa','inv-meses'].forEach(id=>document.getElementById(id).value='');['inv-total','inv-aplicado'].forEach(id=>document.getElementById(id).textContent='-');document.getElementById('tool-detail').textContent='';document.getElementById('tool-result').classList.remove('show');clearError();}function copyTool(button){if(!document.getElementById('tool-result').classList.contains('show')){showError('Calcule o investimento antes de copiar o resultado.');return;}copyToClipboard('Valor acumulado: '+document.getElementById('inv-total').textContent,button);}
</script>
<?php ns_render_page_end(); ?>

