<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/config/bootstrap.php';
ns_redirect_legacy_url('/ferramentas/calculadora-tempo-viagem');
ns_render_page_start('tool:calculadora-tempo-viagem');
?>
<main><div class="tool-page">
  <nav class="breadcrumb" aria-label="Navega��o breadcrumb"><a href="<?= ns_escape(ns_href('/')) ?>">In�cio</a><span class="sep">�</span><a href="<?= ns_escape(ns_href('/ferramentas')) ?>">Ferramentas</a><span class="sep">�</span><span>Calculadora de Tempo de Viagem</span></nav>
  <?php ns_render_ad_slot('leaderboard'); ?>
  <div class="tool-header"><div class="tool-page-icon" style="background:linear-gradient(135deg,#f0f7ff,#d3e2ff);">???</div><div><h1>Calculadora de Tempo de Viagem</h1><p>Descubra quanto tempo uma viagem pode levar usando dist�ncia total e velocidade m�dia estimada.</p><span class="tag tag-blue">Matem�tica</span></div></div>
  <div class="tool-box">
    <div class="form-row"><div class="form-group"><label for="distancia-viagem">Dist�ncia (km)</label><input type="number" id="distancia-viagem" class="form-control" min="0" step="0.01" /></div><div class="form-group"><label for="velocidade-viagem">Velocidade m�dia (km/h)</label><input type="number" id="velocidade-viagem" class="form-control" min="0" step="0.01" /></div></div>
    <div class="form-row"><button type="button" class="btn btn-primary" onclick="calcularTempoViagem()">Calcular tempo</button><button type="button" class="btn btn-outline" onclick="limparTempoViagem()">Limpar</button><button type="button" class="copy-btn" onclick="copiarTempoViagem(this)">Copiar resultado</button></div>
    <div class="notice notice-warn" id="erro-viagem" style="display:none;"><span>??</span><span id="erro-viagem-texto"></span></div>
    <div class="result-box" id="resultado-viagem"><div class="result-grid"><div class="result-item"><div class="label">Tempo em horas</div><div class="value" id="viagem-horas">�</div></div><div class="result-item"><div class="label">Tempo formatado</div><div class="value" id="viagem-formatado">�</div></div></div><div id="viagem-detalhe" style="margin-top:1rem;color:var(--text2);"></div></div>
  </div>
  <?php ns_render_ad_slot('rectangle'); ?>
  <div class="seo-content"><h2>O que � essa ferramenta</h2><p>A calculadora de tempo de viagem ajuda a estimar a dura��o de um deslocamento com base na dist�ncia e na velocidade m�dia esperada. � �til para planejamento de rotas, viagens de carro, entregas, log�stica e organiza��o de compromissos.</p><p>Ela entrega uma resposta imediata no navegador e evita contas manuais, o que melhora usabilidade e mant�m o projeto leve.</p><h2>Como usar</h2><p>Digite a dist�ncia total da viagem em quil�metros e a velocidade m�dia estimada em km/h. Depois clique em calcular. A ferramenta divide a dist�ncia pela velocidade e retorna o tempo em horas e tamb�m em formato horas e minutos.</p><p>Se algum valor estiver vazio, menor que zero ou causar divis�o inv�lida, uma valida��o amig�vel aparece antes do resultado.</p><h2>Exemplo de uso</h2><p>Se uma rota tem 240 km e a velocidade m�dia prevista � 80 km/h, o tempo estimado ser� de 3 horas. Esse tipo de c�lculo � �til para organizar sa�das, prever chegada e at� calcular pausas operacionais.</p><p>Apesar de ser uma estimativa, ele j� oferece uma refer�ncia clara para tomada de decis�o r�pida.</p><h2>Perguntas frequentes</h2><h3>O c�lculo considera tr�nsito e paradas?</h3><p>N�o. Ele usa apenas dist�ncia e velocidade m�dia informadas pelo usu�rio.</p><h3>Posso usar decimal na velocidade?</h3><p>Sim. Valores decimais s�o aceitos normalmente.</p><h3>O resultado mostra minutos?</h3><p>Sim. Al�m das horas decimais, a ferramenta exibe um formato de horas e minutos.</p></div>
  <div class="related-tools"><h2>Ferramentas relacionadas</h2><div class="related-grid"><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-velocidade-media')) ?>" class="related-card"><span class="related-card-icon">??</span> Velocidade M�dia</a><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-regra-de-tres')) ?>" class="related-card"><span class="related-card-icon">??</span> Regra de Tr�s</a><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-area-quadrado')) ?>" class="related-card"><span class="related-card-icon">?</span> �rea do Quadrado</a></div></div>
</div></main>
<script>
function erroViagem(msg){document.getElementById('erro-viagem-texto').textContent=msg;document.getElementById('erro-viagem').style.display='flex';document.getElementById('resultado-viagem').classList.remove('show');}
function limparErroViagem(){document.getElementById('erro-viagem').style.display='none';}
function calcularTempoViagem(){const distancia=parseFloat(document.getElementById('distancia-viagem').value);const velocidade=parseFloat(document.getElementById('velocidade-viagem').value);limparErroViagem();if(isNaN(distancia)||isNaN(velocidade)||distancia<=0||velocidade<=0){erroViagem('Informe dist�ncia e velocidade m�dia maiores que zero.');return;}const horas=distancia/velocidade;const horasInteiras=Math.floor(horas);const minutos=Math.round((horas-horasInteiras)*60);document.getElementById('viagem-horas').textContent=fmtNum(horas,2)+' h';document.getElementById('viagem-formatado').textContent=horasInteiras+'h '+minutos+'min';document.getElementById('viagem-detalhe').textContent='F�rmula aplicada: dist�ncia � velocidade m�dia.';showResult('resultado-viagem');}
function limparTempoViagem(){document.getElementById('distancia-viagem').value='';document.getElementById('velocidade-viagem').value='';document.getElementById('resultado-viagem').classList.remove('show');limparErroViagem();}
function copiarTempoViagem(button){if(!document.getElementById('resultado-viagem').classList.contains('show')){erroViagem('Calcule o tempo antes de copiar o resultado.');return;}copyToClipboard('Tempo da viagem: '+document.getElementById('viagem-formatado').textContent,button);}
</script>
<?php ns_render_page_end(); ?>
