<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/config/bootstrap.php';
ns_redirect_legacy_url('/ferramentas/calculadora-velocidade-media');
ns_render_page_start('tool:calculadora-velocidade-media');
?>
<main><div class="tool-page">
  <nav class="breadcrumb" aria-label="Navega��o breadcrumb"><a href="<?= ns_escape(ns_href('/')) ?>">In�cio</a><span class="sep">�</span><a href="<?= ns_escape(ns_href('/ferramentas')) ?>">Ferramentas</a><span class="sep">�</span><span>Calculadora de Velocidade M�dia</span></nav>
  <?php ns_render_ad_slot('leaderboard'); ?>
  <div class="tool-header"><div class="tool-page-icon" style="background:linear-gradient(135deg,#eef6ff,#cfe1ff);">??</div><div><h1>Calculadora de Velocidade M�dia</h1><p>Calcule km/h de forma r�pida com base na dist�ncia percorrida e no tempo total de deslocamento.</p><span class="tag tag-blue">Matem�tica</span></div></div>
  <div class="tool-box">
    <div class="form-row"><div class="form-group"><label for="distancia-media">Dist�ncia (km)</label><input type="number" id="distancia-media" class="form-control" min="0" step="0.01" /></div><div class="form-group"><label for="tempo-media">Tempo (horas)</label><input type="number" id="tempo-media" class="form-control" min="0" step="0.01" /></div></div>
    <div class="form-row"><button type="button" class="btn btn-primary" onclick="calcularVelocidadeMedia()">Calcular velocidade</button><button type="button" class="btn btn-outline" onclick="limparVelocidadeMedia()">Limpar</button><button type="button" class="copy-btn" onclick="copiarVelocidadeMedia(this)">Copiar resultado</button></div>
    <div class="notice notice-warn" id="erro-velocidade" style="display:none;"><span>??</span><span id="erro-velocidade-texto"></span></div>
    <div class="result-box" id="resultado-velocidade"><div class="result-label">Velocidade m�dia</div><div class="result-value" id="velocidade-valor">�</div><div id="velocidade-detalhe" style="margin-top:1rem;color:var(--text2);"></div></div>
  </div>
  <?php ns_render_ad_slot('rectangle'); ?>
  <div class="seo-content"><h2>O que � essa ferramenta</h2><p>A calculadora de velocidade m�dia foi criada para descobrir rapidamente a rela��o entre dist�ncia percorrida e tempo gasto. � uma conta muito usada em viagens, log�stica, transporte, estudos de f�sica e planejamento de deslocamento.</p><p>Ao fazer o c�lculo diretamente no navegador, a ferramenta oferece resposta instant�nea e ajuda o site a manter alta performance.</p><h2>Como usar</h2><p>Informe a dist�ncia total em quil�metros e o tempo total em horas. Depois clique em calcular. A ferramenta divide a dist�ncia pelo tempo e mostra a velocidade m�dia em km/h. Se o tempo for zero ou inv�lido, uma mensagem de erro amig�vel aparecer� na tela.</p><p>Voc� ainda pode limpar os campos e copiar o resultado final com um clique.</p><h2>Exemplo de uso</h2><p>Se uma viagem teve 180 km e durou 3 horas, a velocidade m�dia foi de 60 km/h. Esse c�lculo n�o representa a velocidade instant�nea em cada trecho, mas uma m�dia do percurso inteiro.</p><p>� �til para comparar viagens, simular rotas e fazer estimativas r�pidas sem abrir planilhas.</p><h2>Perguntas frequentes</h2><h3>Velocidade m�dia � igual � velocidade m�xima?</h3><p>N�o. A velocidade m�dia considera o percurso completo, incluindo varia��es e paradas.</p><h3>Posso usar minutos?</h3><p>Nesta vers�o, o campo de tempo est� em horas. Voc� pode converter minutos para horas antes de calcular.</p><h3>Serve para estudo de f�sica?</h3><p>Sim. � uma ferramenta simples e pr�tica para exerc�cios introdut�rios.</p></div>
  <div class="related-tools"><h2>Ferramentas relacionadas</h2><div class="related-grid"><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-tempo-viagem')) ?>" class="related-card"><span class="related-card-icon">???</span> Tempo de Viagem</a><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-regra-de-tres')) ?>" class="related-card"><span class="related-card-icon">??</span> Regra de Tr�s</a><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-porcentagem')) ?>" class="related-card"><span class="related-card-icon">%</span> Calculadora de Porcentagem</a></div></div>
</div></main>
<script>
function erroVelocidade(msg){document.getElementById('erro-velocidade-texto').textContent=msg;document.getElementById('erro-velocidade').style.display='flex';document.getElementById('resultado-velocidade').classList.remove('show');}
function limparErroVelocidade(){document.getElementById('erro-velocidade').style.display='none';}
function calcularVelocidadeMedia(){const distancia=parseFloat(document.getElementById('distancia-media').value);const tempo=parseFloat(document.getElementById('tempo-media').value);limparErroVelocidade();if(isNaN(distancia)||isNaN(tempo)||distancia<=0||tempo<=0){erroVelocidade('Informe dist�ncia e tempo maiores que zero.');return;}const velocidade=distancia/tempo;document.getElementById('velocidade-valor').textContent=fmtNum(velocidade,2)+' km/h';document.getElementById('velocidade-detalhe').textContent='F�rmula usada: dist�ncia � tempo = '+fmtNum(distancia,2)+' � '+fmtNum(tempo,2)+'.';showResult('resultado-velocidade');}
function limparVelocidadeMedia(){document.getElementById('distancia-media').value='';document.getElementById('tempo-media').value='';document.getElementById('resultado-velocidade').classList.remove('show');limparErroVelocidade();}
function copiarVelocidadeMedia(button){if(!document.getElementById('resultado-velocidade').classList.contains('show')){erroVelocidade('Calcule a velocidade antes de copiar o resultado.');return;}copyToClipboard('Velocidade m�dia: '+document.getElementById('velocidade-valor').textContent,button);}
</script>
<?php ns_render_page_end(); ?>
