<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/config/bootstrap.php';
ns_redirect_legacy_url('/ferramentas/calculadora-fgts');
ns_render_page_start('tool:calculadora-fgts');
?>
<main><div class="tool-page">
  <nav class="breadcrumb" aria-label="Navegação breadcrumb"><a href="<?= ns_escape(ns_href('/')) ?>">Início</a><span class="sep">›</span><a href="<?= ns_escape(ns_href('/ferramentas')) ?>">Ferramentas</a><span class="sep">›</span><span>Calculadora de FGTS</span></nav>
  <?php ns_render_ad_slot('leaderboard'); ?>
  <div class="tool-header"><div class="tool-page-icon" style="background:linear-gradient(135deg,#edf9f1,#d6f0df);">📦</div><div><h1>Calculadora de FGTS</h1><p>Estime o depósito mensal de FGTS a partir do salário bruto do trabalhador.</p><span class="tag tag-green">Finanças</span></div></div>
  <div class="tool-box">
    <div class="form-row"><div class="form-group"><label for="fgts-salario">Salário bruto mensal (R$)</label><input type="number" id="fgts-salario" class="form-control" min="0" step="0.01" placeholder="Ex: 3200" /></div></div>
    <div class="form-row"><button type="button" class="btn btn-primary" onclick="runTool()">Calcular FGTS</button><button type="button" class="btn btn-outline" onclick="clearTool()">Limpar</button><button type="button" class="copy-btn" onclick="copyTool(this)">Copiar resultado</button></div>
    <div class="notice notice-warn" id="tool-error" style="display:none;"><span>⚠️</span><span id="tool-error-text"></span></div>
    <div class="result-box" id="tool-result"><div class="result-label">Estimativa do FGTS</div><div class="result-grid"><div class="result-item"><div class="label">Depósito mensal</div><div class="value" id="fgts-valor">-</div></div><div class="result-item"><div class="label">Estimativa em 12 meses</div><div class="value" id="fgts-anual">-</div></div></div><div id="tool-detail" style="margin-top:1rem;color:var(--text2);"></div></div>
  </div>
  <?php ns_render_ad_slot('rectangle'); ?>
<div class="seo-content"><h2>O que é essa ferramenta</h2><p>A calculadora de FGTS ajuda a descobrir quanto pode ser depositado mensalmente no fundo com base no salário bruto. Ela é útil para planejamento financeiro, conferência trabalhista e acompanhamento de valores acumulados.</p><p>O cálculo roda em JavaScript puro no navegador, o que ajuda a manter a página rápida, leve e fácil de usar em qualquer dispositivo. A estrutura também foi pensada para SEO, com conteúdo explicativo, headings claros e foco em intenção de busca real.</p><h2>Como usar</h2><p>Digite o salário bruto mensal e clique em calcular. A ferramenta aplica a alíquota padrão de 8% e mostra tanto o depósito mensal quanto uma projeção anual simples.</p><p>Se algum campo estiver vazio ou com valor inválido, a ferramenta mostra uma mensagem amigável antes de liberar o resultado. Depois, você pode copiar a resposta ou limpar tudo para uma nova simulação.</p><h2>Exemplo de uso</h2><p>Quem recebe R$ 3.200 por mês pode usar a ferramenta para ver quanto representa o depósito mensal de FGTS e qual seria o total aproximado após um ano.</p><p>Esse contexto adicional torna a página mais útil para visitantes que chegam pela busca orgânica e precisam de uma resposta prática, mas também querem entender como aplicar o resultado.</p><h2>Perguntas frequentes</h2><h3>Esse valor sai do salário líquido?</h3><p>Não. O FGTS é um depósito do empregador, não um desconto direto no salário do trabalhador.</p><h3>Serve para planejamento?</h3><p>Sim. É útil para ter uma visão prática do valor acumulado.</p><h3>O cálculo considera juros do fundo?</h3><p>Não. A projeção anual exibida é simples, sem rendimento adicional.</p></div>
  <div class="related-tools"><h2>Ferramentas relacionadas</h2><div class="related-grid"><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-inss')) ?>" class="related-card"><span class="related-card-icon">🏛️</span> INSS</a><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-imposto-renda')) ?>" class="related-card"><span class="related-card-icon">🧾</span> Imposto de Renda</a><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-salario-liquido')) ?>" class="related-card"><span class="related-card-icon">💼</span> Salário Líquido</a></div></div>
</div></main>
<script>
function showError(message){document.getElementById('tool-error-text').textContent=message;document.getElementById('tool-error').style.display='flex';document.getElementById('tool-result').classList.remove('show');}
function clearError(){document.getElementById('tool-error').style.display='none';}
function runTool(){const salario=parseFloat(document.getElementById('fgts-salario').value);clearError();if(isNaN(salario)||salario<=0){showError('Informe um salário bruto válido maior que zero.');return;}const mensal=salario*0.08;document.getElementById('fgts-valor').textContent='R$ '+fmtBRL(mensal);document.getElementById('fgts-anual').textContent='R$ '+fmtBRL(mensal*12);document.getElementById('tool-detail').textContent='Cálculo com alíquota padrão de 8% sobre o salário bruto.';showResult('tool-result');}function clearTool(){document.getElementById('fgts-salario').value='';['fgts-valor','fgts-anual'].forEach(id=>document.getElementById(id).textContent='-');document.getElementById('tool-detail').textContent='';document.getElementById('tool-result').classList.remove('show');clearError();}function copyTool(button){if(!document.getElementById('tool-result').classList.contains('show')){showError('Calcule o FGTS antes de copiar o resultado.');return;}copyToClipboard('FGTS mensal: '+document.getElementById('fgts-valor').textContent+'\nFGTS anual: '+document.getElementById('fgts-anual').textContent,button);}
</script>
<?php ns_render_page_end(); ?>

