<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/config/bootstrap.php';
ns_redirect_legacy_url('/ferramentas/calculadora-aluguel-reajuste');
ns_render_page_start('tool:calculadora-aluguel-reajuste');
?>
<main><div class="tool-page">
  <nav class="breadcrumb" aria-label="Navegação breadcrumb"><a href="<?= ns_escape(ns_href('/')) ?>">Início</a><span class="sep">›</span><a href="<?= ns_escape(ns_href('/ferramentas')) ?>">Ferramentas</a><span class="sep">›</span><span>Calculadora de Reajuste de Aluguel</span></nav>
  <?php ns_render_ad_slot('leaderboard'); ?>
  <div class="tool-header"><div class="tool-page-icon" style="background:linear-gradient(135deg,#eef7ff,#d9e9ff);">🏠</div><div><h1>Calculadora de Reajuste de Aluguel</h1><p>Simule o novo valor do aluguel após aplicar um índice ou percentual de reajuste.</p><span class="tag tag-green">Finanças</span></div></div>
  <div class="tool-box">
    <div class="form-row"><div class="form-group"><label for="aluguel-valor">Aluguel atual (R$)</label><input type="number" id="aluguel-valor" class="form-control" min="0" step="0.01" placeholder="Ex: 1800" /></div><div class="form-group"><label for="aluguel-taxa">Reajuste (%)</label><input type="number" id="aluguel-taxa" class="form-control" min="0" step="0.01" placeholder="Ex: 7.5" /></div></div>
    <div class="form-row"><button type="button" class="btn btn-primary" onclick="runTool()">Calcular reajuste</button><button type="button" class="btn btn-outline" onclick="clearTool()">Limpar</button><button type="button" class="copy-btn" onclick="copyTool(this)">Copiar resultado</button></div>
    <div class="notice notice-warn" id="tool-error" style="display:none;"><span>⚠️</span><span id="tool-error-text"></span></div>
    <div class="result-box" id="tool-result"><div class="result-label">Novo valor do aluguel</div><div class="result-grid"><div class="result-item"><div class="label">Novo aluguel</div><div class="value" id="aluguel-novo">-</div></div><div class="result-item"><div class="label">Aumento</div><div class="value" id="aluguel-diferenca">-</div></div></div><div id="tool-detail" style="margin-top:1rem;color:var(--text2);"></div></div>
  </div>
  <?php ns_render_ad_slot('rectangle'); ?>
<div class="seo-content"><h2>O que é essa ferramenta</h2><p>A calculadora de reajuste de aluguel ajuda a descobrir rapidamente quanto um aluguel passa a custar depois da aplicação de um índice ou percentual de reajuste. É útil para locadores, locatários e administradoras.</p><p>O cálculo roda em JavaScript puro no navegador, o que ajuda a manter a página rápida, leve e fácil de usar em qualquer dispositivo. A estrutura também foi pensada para SEO, com conteúdo explicativo, headings claros e foco em intenção de busca real.</p><h2>Como usar</h2><p>Informe o valor atual do aluguel e o percentual de reajuste desejado. A ferramenta exibe o novo valor mensal e a diferença entre o aluguel antigo e o reajustado.</p><p>Se algum campo estiver vazio ou com valor inválido, a ferramenta mostra uma mensagem amigável antes de liberar o resultado. Depois, você pode copiar a resposta ou limpar tudo para uma nova simulação.</p><h2>Exemplo de uso</h2><p>Se um aluguel de R$ 1.800 receber reajuste de 7,5%, a ferramenta calcula o novo valor e mostra o aumento em reais.</p><p>Esse contexto adicional torna a página mais útil para visitantes que chegam pela busca orgânica e precisam de uma resposta prática, mas também querem entender como aplicar o resultado.</p><h2>Perguntas frequentes</h2><h3>Serve para imóvel residencial e comercial?</h3><p>Sim. O cálculo percentual funciona da mesma forma para ambos.</p><h3>O índice é oficial?</h3><p>Você informa a taxa desejada e a ferramenta apenas aplica esse percentual.</p><h3>Posso usar em renegociação?</h3><p>Sim. É muito útil para simular cenários antes de conversar sobre o contrato.</p></div>
  <div class="related-tools"><h2>Ferramentas relacionadas</h2><div class="related-grid"><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-correcao-monetaria')) ?>" class="related-card"><span class="related-card-icon">📊</span> Correção Monetária</a><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-inflacao')) ?>" class="related-card"><span class="related-card-icon">📈</span> Inflação</a><a href="<?= ns_escape(ns_href('/ferramentas/simulador-financiamento')) ?>" class="related-card"><span class="related-card-icon">🏠</span> Financiamento</a></div></div>
</div></main>
<script>
function showError(message){document.getElementById('tool-error-text').textContent=message;document.getElementById('tool-error').style.display='flex';document.getElementById('tool-result').classList.remove('show');}
function clearError(){document.getElementById('tool-error').style.display='none';}
function runTool(){const valor=parseFloat(document.getElementById('aluguel-valor').value);const taxa=parseFloat(document.getElementById('aluguel-taxa').value);clearError();if(isNaN(valor)||isNaN(taxa)||valor<0||taxa<0){showError('Informe aluguel e reajuste com valores válidos.');return;}const aumento=valor*(taxa/100);const novo=valor+aumento;document.getElementById('aluguel-novo').textContent='R$ '+fmtBRL(novo);document.getElementById('aluguel-diferenca').textContent='R$ '+fmtBRL(aumento);document.getElementById('tool-detail').textContent='Reajuste percentual simples aplicado ao valor atual do aluguel.';showResult('tool-result');}function clearTool(){['aluguel-valor','aluguel-taxa'].forEach(id=>document.getElementById(id).value='');['aluguel-novo','aluguel-diferenca'].forEach(id=>document.getElementById(id).textContent='-');document.getElementById('tool-detail').textContent='';document.getElementById('tool-result').classList.remove('show');clearError();}function copyTool(button){if(!document.getElementById('tool-result').classList.contains('show')){showError('Calcule o reajuste antes de copiar o resultado.');return;}copyToClipboard('Novo aluguel: '+document.getElementById('aluguel-novo').textContent,button);}
</script>
<?php ns_render_page_end(); ?>

