<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/config/bootstrap.php';
ns_redirect_legacy_url('/ferramentas/calculadora-potencia');
ns_render_page_start('tool:calculadora-potencia');
?>
<main><div class="tool-page">
  <nav class="breadcrumb" aria-label="Navegação breadcrumb"><a href="<?= ns_escape(ns_href('/')) ?>">Início</a><span class="sep">›</span><a href="<?= ns_escape(ns_href('/ferramentas')) ?>">Ferramentas</a><span class="sep">›</span><span>Calculadora de Potência</span></nav>
  <?php ns_render_ad_slot('leaderboard'); ?>
  <div class="tool-header"><div class="tool-page-icon" style="background:linear-gradient(135deg,#f7f3ff,#e3d9ff);">xʸ</div><div><h1>Calculadora de Potência</h1><p>Eleve uma base a um expoente com cálculo rápido e resposta imediata no navegador.</p><span class="tag tag-green">Matemática</span></div></div>
  <div class="tool-box">
    <div class="form-row"><div class="form-group"><label for="pot-base">Base</label><input type="number" id="pot-base" class="form-control" min="-999999" step="0.01" placeholder="Ex: 2" /></div><div class="form-group"><label for="pot-exp">Expoente</label><input type="number" id="pot-exp" class="form-control" min="-999999" step="0.01" placeholder="Ex: 8" /></div></div>
    <div class="form-row"><button type="button" class="btn btn-primary" onclick="runTool()">Calcular potência</button><button type="button" class="btn btn-outline" onclick="clearTool()">Limpar</button><button type="button" class="copy-btn" onclick="copyTool(this)">Copiar resultado</button></div>
    <div class="notice notice-warn" id="tool-error" style="display:none;"><span>⚠️</span><span id="tool-error-text"></span></div>
    <div class="result-box" id="tool-result"><div class="result-label">Resultado da potência</div><div class="result-grid"><div class="result-item"><div class="label">Potência</div><div class="value" id="pot-valor">-</div></div><div class="result-item"><div class="label">Resumo</div><div class="value" id="pot-baseinfo">-</div></div></div><div id="tool-detail" style="margin-top:1rem;color:var(--text2);"></div></div>
  </div>
  <?php ns_render_ad_slot('rectangle'); ?>
<div class="seo-content"><h2>O que é essa ferramenta</h2><p>A calculadora de potência mostra o resultado de uma base elevada a um expoente. Ela é útil em matemática, física, programação, eletrônica e cálculos financeiros.</p><p>O cálculo roda em JavaScript puro no navegador, o que ajuda a manter a página rápida, leve e fácil de usar em qualquer dispositivo. A estrutura também foi pensada para SEO, com conteúdo explicativo, headings claros e foco em intenção de busca real.</p><h2>Como usar</h2><p>Digite base e expoente nos campos indicados e clique em calcular. A ferramenta processa a conta rapidamente e mostra o resultado com uma breve explicação da operação.</p><p>Se algum campo estiver vazio ou com valor inválido, a ferramenta mostra uma mensagem amigável antes de liberar o resultado. Depois, você pode copiar a resposta ou limpar tudo para uma nova simulação.</p><h2>Exemplo de uso</h2><p>Ao elevar 2 a 8, o resultado é 256. Esse tipo de cálculo é muito comum em exercícios, análises técnicas e comparações de crescimento exponencial.</p><p>Esse contexto adicional torna a página mais útil para visitantes que chegam pela busca orgânica e precisam de uma resposta prática, mas também querem entender como aplicar o resultado.</p><h2>Perguntas frequentes</h2><h3>Aceita expoente decimal?</h3><p>Sim. A ferramenta aceita valores decimais para base e expoente.</p><h3>Posso usar base negativa?</h3><p>Sim, desde que a operação resulte em valor numérico válido no navegador.</p><h3>Serve para estudo?</h3><p>Sim. É excelente para praticar e conferir contas.</p></div>
  <div class="related-tools"><h2>Ferramentas relacionadas</h2><div class="related-grid"><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-raiz-quadrada')) ?>" class="related-card"><span class="related-card-icon">√</span> Raiz Quadrada</a><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-area-quadrado')) ?>" class="related-card"><span class="related-card-icon">⬜</span> Área do Quadrado</a><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-regra-de-tres')) ?>" class="related-card"><span class="related-card-icon">📐</span> Regra de Três</a></div></div>
</div></main>
<script>
function showError(message){document.getElementById('tool-error-text').textContent=message;document.getElementById('tool-error').style.display='flex';document.getElementById('tool-result').classList.remove('show');}
function clearError(){document.getElementById('tool-error').style.display='none';}
function runTool(){const base=parseFloat(document.getElementById('pot-base').value);const exp=parseFloat(document.getElementById('pot-exp').value);clearError();if(isNaN(base)||isNaN(exp)){showError('Preencha base e expoente com valores válidos.');return;}const valor=Math.pow(base,exp);if(!isFinite(valor)){showError('O resultado não pode ser exibido com os valores informados.');return;}document.getElementById('pot-valor').textContent=fmtNum(valor,6);document.getElementById('pot-baseinfo').textContent=fmtNum(base,6)+' ^ '+fmtNum(exp,6);document.getElementById('tool-detail').textContent='A conta representa a base multiplicada por ela mesma conforme o expoente.';showResult('tool-result');}function clearTool(){['pot-base','pot-exp'].forEach(id=>document.getElementById(id).value='');['pot-valor','pot-baseinfo'].forEach(id=>document.getElementById(id).textContent='-');document.getElementById('tool-detail').textContent='';document.getElementById('tool-result').classList.remove('show');clearError();}function copyTool(button){if(!document.getElementById('tool-result').classList.contains('show')){showError('Calcule a potência antes de copiar o resultado.');return;}copyToClipboard('Potência: '+document.getElementById('pot-valor').textContent,button);}
</script>
<?php ns_render_page_end(); ?>

