<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/config/bootstrap.php';
ns_redirect_legacy_url('/ferramentas/calculadora-emprestimo');
ns_render_page_start('tool:calculadora-emprestimo');
?>
<main><div class="tool-page">
  <nav class="breadcrumb" aria-label="Navegação breadcrumb"><a href="<?= ns_escape(ns_href('/')) ?>">Início</a><span class="sep">›</span><a href="<?= ns_escape(ns_href('/ferramentas')) ?>">Ferramentas</a><span class="sep">›</span><span>Calculadora de Empréstimo</span></nav>
  <?php ns_render_ad_slot('leaderboard'); ?>
  <div class="tool-header"><div class="tool-page-icon" style="background:linear-gradient(135deg,#fff5ef,#ffe0c8);">💳</div><div><h1>Calculadora de Empréstimo</h1><p>Simule parcelas e valor total de um empréstimo usando taxa de juros e prazo.</p><span class="tag tag-green">Finanças</span></div></div>
  <div class="tool-box">
    <div class="form-row"><div class="form-group"><label for="emp-valor">Valor do empréstimo (R$)</label><input type="number" id="emp-valor" class="form-control" min="0" step="0.01" placeholder="Ex: 10000" /></div><div class="form-group"><label for="emp-juros">Juros ao mês (%)</label><input type="number" id="emp-juros" class="form-control" min="0" step="0.01" placeholder="Ex: 2.5" /></div><div class="form-group"><label for="emp-meses">Prazo em meses</label><input type="number" id="emp-meses" class="form-control" min="1" step="1" placeholder="Ex: 24" /></div></div>
    <div class="form-row"><button type="button" class="btn btn-primary" onclick="runTool()">Calcular empréstimo</button><button type="button" class="btn btn-outline" onclick="clearTool()">Limpar</button><button type="button" class="copy-btn" onclick="copyTool(this)">Copiar resultado</button></div>
    <div class="notice notice-warn" id="tool-error" style="display:none;"><span>⚠️</span><span id="tool-error-text"></span></div>
    <div class="result-box" id="tool-result"><div class="result-label">Simulação do empréstimo</div><div class="result-grid"><div class="result-item"><div class="label">Parcela estimada</div><div class="value" id="emp-parcela">-</div></div><div class="result-item"><div class="label">Total pago</div><div class="value" id="emp-total">-</div></div></div><div id="tool-detail" style="margin-top:1rem;color:var(--text2);"></div></div>
  </div>
  <?php ns_render_ad_slot('rectangle'); ?>
<div class="seo-content"><h2>O que é essa ferramenta</h2><p>A calculadora de empréstimo ajuda a estimar quanto pode ficar a parcela de um crédito com base no valor principal, na taxa de juros mensal e no prazo de pagamento. Ela é útil para comparação de propostas e análise de capacidade de pagamento.</p><p>O cálculo roda em JavaScript puro no navegador, o que ajuda a manter a página rápida, leve e fácil de usar em qualquer dispositivo. A estrutura também foi pensada para SEO, com conteúdo explicativo, headings claros e foco em intenção de busca real.</p><h2>Como usar</h2><p>Informe o valor do empréstimo, os juros mensais e o número de meses. A ferramenta calcula uma parcela estimada e mostra o total pago ao final do contrato.</p><p>Se algum campo estiver vazio ou com valor inválido, a ferramenta mostra uma mensagem amigável antes de liberar o resultado. Depois, você pode copiar a resposta ou limpar tudo para uma nova simulação.</p><h2>Exemplo de uso</h2><p>Se uma pessoa quer contratar R$ 10.000 com juros de 2,5% ao mês por 24 meses, a calculadora ajuda a entender o peso da parcela e o custo total do crédito.</p><p>Esse contexto adicional torna a página mais útil para visitantes que chegam pela busca orgânica e precisam de uma resposta prática, mas também querem entender como aplicar o resultado.</p><h2>Perguntas frequentes</h2><h3>Esse cálculo é igual ao do banco?</h3><p>É uma simulação útil para comparação inicial, mas o contrato oficial pode ter custos extras.</p><h3>Serve para crédito pessoal?</h3><p>Sim. É especialmente útil para esse tipo de análise.</p><h3>Posso testar vários prazos?</h3><p>Sim. É uma boa forma de comparar cenários.</p></div>
  <div class="related-tools"><h2>Ferramentas relacionadas</h2><div class="related-grid"><a href="<?= ns_escape(ns_href('/ferramentas/simulador-financiamento')) ?>" class="related-card"><span class="related-card-icon">🏠</span> Financiamento</a><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-cartao-credito')) ?>" class="related-card"><span class="related-card-icon">💳</span> Cartão de Crédito</a><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-juros-atraso')) ?>" class="related-card"><span class="related-card-icon">📅</span> Juros por Atraso</a></div></div>
</div></main>
<script>
function showError(message){document.getElementById('tool-error-text').textContent=message;document.getElementById('tool-error').style.display='flex';document.getElementById('tool-result').classList.remove('show');}
function clearError(){document.getElementById('tool-error').style.display='none';}
function runTool(){const pv=parseFloat(document.getElementById('emp-valor').value);const juros=parseFloat(document.getElementById('emp-juros').value)/100;const meses=parseInt(document.getElementById('emp-meses').value,10);clearError();if(isNaN(pv)||isNaN(juros)||isNaN(meses)||pv<=0||juros<0||meses<=0){showError('Preencha valor, juros e prazo com números válidos.');return;}const parcela=juros===0?pv/meses:(pv*juros)/(1-Math.pow(1+juros,-meses));const total=parcela*meses;document.getElementById('emp-parcela').textContent='R$ '+fmtBRL(parcela);document.getElementById('emp-total').textContent='R$ '+fmtBRL(total);document.getElementById('tool-detail').textContent='Simulação com prestação constante para apoio de análise.';showResult('tool-result');}function clearTool(){['emp-valor','emp-juros','emp-meses'].forEach(id=>document.getElementById(id).value='');['emp-parcela','emp-total'].forEach(id=>document.getElementById(id).textContent='-');document.getElementById('tool-detail').textContent='';document.getElementById('tool-result').classList.remove('show');clearError();}function copyTool(button){if(!document.getElementById('tool-result').classList.contains('show')){showError('Calcule o empréstimo antes de copiar o resultado.');return;}copyToClipboard('Parcela: '+document.getElementById('emp-parcela').textContent+'\nTotal pago: '+document.getElementById('emp-total').textContent,button);}
</script>
<?php ns_render_page_end(); ?>

