<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/config/bootstrap.php';
ns_redirect_legacy_url('/ferramentas/calculadora-imposto-renda');
ns_render_page_start('tool:calculadora-imposto-renda');
?>
<main><div class="tool-page">
  <nav class="breadcrumb" aria-label="Navegação breadcrumb"><a href="<?= ns_escape(ns_href('/')) ?>">Início</a><span class="sep">›</span><a href="<?= ns_escape(ns_href('/ferramentas')) ?>">Ferramentas</a><span class="sep">›</span><span>Calculadora de Imposto de Renda</span></nav>
  <?php ns_render_ad_slot('leaderboard'); ?>
  <div class="tool-header"><div class="tool-page-icon" style="background:linear-gradient(135deg,#eef8ff,#d6ebff);">🧾</div><div><h1>Calculadora de Imposto de Renda</h1><p>Estime o imposto de renda mensal a partir do salário bruto e das deduções informadas.</p><span class="tag tag-green">Finanças</span></div></div>
  <div class="tool-box">
    <div class="form-row"><div class="form-group"><label for="ir-salario">Salário bruto mensal (R$)</label><input type="number" id="ir-salario" class="form-control" min="0" step="0.01" placeholder="Ex: 6000" /></div><div class="form-group"><label for="ir-inss">Desconto de INSS (R$)</label><input type="number" id="ir-inss" class="form-control" min="0" step="0.01" placeholder="Ex: 700" /></div><div class="form-group"><label for="ir-dependentes">Número de dependentes</label><input type="number" id="ir-dependentes" class="form-control" min="0" step="1" placeholder="Ex: 1" /></div></div>
    <div class="form-row"><button type="button" class="btn btn-primary" onclick="runTool()">Calcular imposto</button><button type="button" class="btn btn-outline" onclick="clearTool()">Limpar</button><button type="button" class="copy-btn" onclick="copyTool(this)">Copiar resultado</button></div>
    <div class="notice notice-warn" id="tool-error" style="display:none;"><span>⚠️</span><span id="tool-error-text"></span></div>
    <div class="result-box" id="tool-result"><div class="result-label">Estimativa do imposto</div><div class="result-grid"><div class="result-item"><div class="label">Base de cálculo</div><div class="value" id="ir-base">-</div></div><div class="result-item"><div class="label">Imposto estimado</div><div class="value" id="ir-valor">-</div></div></div><div id="tool-detail" style="margin-top:1rem;color:var(--text2);"></div></div>
  </div>
  <?php ns_render_ad_slot('rectangle'); ?>
<div class="seo-content"><h2>O que é essa ferramenta</h2><p>A calculadora de imposto de renda ajuda a estimar quanto pode ser descontado do salário mensal após considerar base tributável, INSS e dependentes. Ela é útil para planejamento financeiro, conferência de holerite e comparação de renda líquida.</p><p>O cálculo roda em JavaScript puro no navegador, o que ajuda a manter a página rápida, leve e fácil de usar em qualquer dispositivo. A estrutura também foi pensada para SEO, com conteúdo explicativo, headings claros e foco em intenção de busca real.</p><h2>Como usar</h2><p>Informe o salário bruto, o valor de INSS e a quantidade de dependentes. A ferramenta calcula uma base simplificada de IR mensal e apresenta a estimativa do imposto com linguagem clara.</p><p>Se algum campo estiver vazio ou com valor inválido, a ferramenta mostra uma mensagem amigável antes de liberar o resultado. Depois, você pode copiar a resposta ou limpar tudo para uma nova simulação.</p><h2>Exemplo de uso</h2><p>Se uma pessoa recebe R$ 6.000 por mês, paga R$ 700 de INSS e possui 1 dependente, a ferramenta estima a base tributável e o imposto mensal correspondente.</p><p>Esse contexto adicional torna a página mais útil para visitantes que chegam pela busca orgânica e precisam de uma resposta prática, mas também querem entender como aplicar o resultado.</p><h2>Perguntas frequentes</h2><h3>Esse cálculo substitui a tabela oficial?</h3><p>Não. Ele é uma estimativa prática para apoio financeiro e conferência inicial.</p><h3>Serve para autônomos?</h3><p>Serve como referência básica, mas não substitui apuração oficial para outros regimes.</p><h3>A dedução por dependente é considerada?</h3><p>Sim. A ferramenta aplica uma dedução simplificada por dependente informado.</p></div>
  <div class="related-tools"><h2>Ferramentas relacionadas</h2><div class="related-grid"><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-inss')) ?>" class="related-card"><span class="related-card-icon">🏛️</span> INSS</a><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-salario-liquido')) ?>" class="related-card"><span class="related-card-icon">💼</span> Salário Líquido</a><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-fgts')) ?>" class="related-card"><span class="related-card-icon">📦</span> FGTS</a></div></div>
</div></main>
<script>
function showError(message){document.getElementById('tool-error-text').textContent=message;document.getElementById('tool-error').style.display='flex';document.getElementById('tool-result').classList.remove('show');}
function clearError(){document.getElementById('tool-error').style.display='none';}
function runTool(){const salario=parseFloat(document.getElementById('ir-salario').value);const inss=parseFloat(document.getElementById('ir-inss').value)||0;const dependentes=parseInt(document.getElementById('ir-dependentes').value||'0',10);clearError();if(isNaN(salario)||salario<=0||isNaN(inss)||inss<0||isNaN(dependentes)||dependentes<0){showError('Preencha salário, INSS e dependentes com valores válidos.');return;}const deducaoDependente=189.59*dependentes;const base=Math.max(0,salario-inss-deducaoDependente);let imposto=0;if(base<=2259.20){imposto=0;}else if(base<=2826.65){imposto=(base*0.075)-169.44;}else if(base<=3751.05){imposto=(base*0.15)-381.44;}else if(base<=4664.68){imposto=(base*0.225)-662.77;}else{imposto=(base*0.275)-896.00;}imposto=Math.max(0,imposto);document.getElementById('ir-base').textContent='R$ '+fmtBRL(base);document.getElementById('ir-valor').textContent='R$ '+fmtBRL(imposto);document.getElementById('tool-detail').textContent='Estimativa simplificada de IR mensal para apoio de planejamento.';showResult('tool-result');}function clearTool(){['ir-salario','ir-inss','ir-dependentes'].forEach(id=>document.getElementById(id).value='');['ir-base','ir-valor'].forEach(id=>document.getElementById(id).textContent='-');document.getElementById('tool-detail').textContent='';document.getElementById('tool-result').classList.remove('show');clearError();}function copyTool(button){if(!document.getElementById('tool-result').classList.contains('show')){showError('Calcule o imposto antes de copiar o resultado.');return;}copyToClipboard('Base: '+document.getElementById('ir-base').textContent+'\nImposto estimado: '+document.getElementById('ir-valor').textContent,button);}
</script>
<?php ns_render_page_end(); ?>

