<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/config/bootstrap.php';
ns_redirect_legacy_url('/ferramentas/calculadora-raiz-quadrada');
ns_render_page_start('tool:calculadora-raiz-quadrada');
?>
<main><div class="tool-page">
  <nav class="breadcrumb" aria-label="Navegação breadcrumb"><a href="<?= ns_escape(ns_href('/')) ?>">Início</a><span class="sep">›</span><a href="<?= ns_escape(ns_href('/ferramentas')) ?>">Ferramentas</a><span class="sep">›</span><span>Calculadora de Raiz Quadrada</span></nav>
  <?php ns_render_ad_slot('leaderboard'); ?>
  <div class="tool-header"><div class="tool-page-icon" style="background:linear-gradient(135deg,#eefaf7,#d9f4ea);">√</div><div><h1>Calculadora de Raiz Quadrada</h1><p>Calcule a raiz quadrada de um número com resposta imediata e interpretação simples.</p><span class="tag tag-green">Matemática</span></div></div>
  <div class="tool-box">
    <div class="form-row"><div class="form-group"><label for="raiz-numero">Número</label><input type="number" id="raiz-numero" class="form-control" min="0" step="0.01" placeholder="Ex: 144" /></div></div>
    <div class="form-row"><button type="button" class="btn btn-primary" onclick="runTool()">Calcular raiz</button><button type="button" class="btn btn-outline" onclick="clearTool()">Limpar</button><button type="button" class="copy-btn" onclick="copyTool(this)">Copiar resultado</button></div>
    <div class="notice notice-warn" id="tool-error" style="display:none;"><span>⚠️</span><span id="tool-error-text"></span></div>
    <div class="result-box" id="tool-result"><div class="result-label">Resultado da raiz quadrada</div><div class="result-grid"><div class="result-item"><div class="label">Raiz quadrada</div><div class="value" id="raiz-valor">-</div></div><div class="result-item"><div class="label">Verificação</div><div class="value" id="raiz-verificacao">-</div></div></div><div id="tool-detail" style="margin-top:1rem;color:var(--text2);"></div></div>
  </div>
  <?php ns_render_ad_slot('rectangle'); ?>
<div class="seo-content"><h2>O que é essa ferramenta</h2><p>A calculadora de raiz quadrada ajuda a descobrir qual valor multiplicado por ele mesmo gera o número informado. Ela é útil em matemática escolar, física, engenharia, estatística e conferências rápidas de cálculos.</p><p>O cálculo roda em JavaScript puro no navegador, o que ajuda a manter a página rápida, leve e fácil de usar em qualquer dispositivo. A estrutura também foi pensada para SEO, com conteúdo explicativo, headings claros e foco em intenção de busca real.</p><h2>Como usar</h2><p>Digite um número maior ou igual a zero e clique em calcular. A ferramenta mostra a raiz quadrada e ainda resume uma verificação da operação para facilitar entendimento.</p><p>Se algum campo estiver vazio ou com valor inválido, a ferramenta mostra uma mensagem amigável antes de liberar o resultado. Depois, você pode copiar a resposta ou limpar tudo para uma nova simulação.</p><h2>Exemplo de uso</h2><p>Se você informar 144, a calculadora retorna 12 e também deixa claro que 12 multiplicado por 12 gera 144.</p><p>Esse contexto adicional torna a página mais útil para visitantes que chegam pela busca orgânica e precisam de uma resposta prática, mas também querem entender como aplicar o resultado.</p><h2>Perguntas frequentes</h2><h3>Aceita número decimal?</h3><p>Sim. A calculadora aceita números com casas decimais.</p><h3>Posso usar número negativo?</h3><p>Nesta versão, a ferramenta trabalha com raízes reais e usa valores a partir de zero.</p><h3>Serve para estudo?</h3><p>Sim. Ela é muito útil para conferência e aprendizado.</p></div>
  <div class="related-tools"><h2>Ferramentas relacionadas</h2><div class="related-grid"><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-potencia')) ?>" class="related-card"><span class="related-card-icon">xʸ</span> Potência</a><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-porcentagem')) ?>" class="related-card"><span class="related-card-icon">%</span> Porcentagem</a><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-regra-de-tres')) ?>" class="related-card"><span class="related-card-icon">📐</span> Regra de Três</a></div></div>
</div></main>
<script>
function showError(message){document.getElementById('tool-error-text').textContent=message;document.getElementById('tool-error').style.display='flex';document.getElementById('tool-result').classList.remove('show');}
function clearError(){document.getElementById('tool-error').style.display='none';}
function runTool(){const numero=parseFloat(document.getElementById('raiz-numero').value);clearError();if(isNaN(numero)||numero<0){showError('Informe um número válido maior ou igual a zero.');return;}const raiz=Math.sqrt(numero);document.getElementById('raiz-valor').textContent=fmtNum(raiz,6);document.getElementById('raiz-verificacao').textContent=fmtNum(raiz*raiz,6);document.getElementById('tool-detail').textContent='A verificação mostra o valor da raiz multiplicado por ele mesmo.';showResult('tool-result');}function clearTool(){document.getElementById('raiz-numero').value='';['raiz-valor','raiz-verificacao'].forEach(id=>document.getElementById(id).textContent='-');document.getElementById('tool-detail').textContent='';document.getElementById('tool-result').classList.remove('show');clearError();}function copyTool(button){if(!document.getElementById('tool-result').classList.contains('show')){showError('Calcule a raiz antes de copiar o resultado.');return;}copyToClipboard('Raiz quadrada: '+document.getElementById('raiz-valor').textContent,button);}
</script>
<?php ns_render_page_end(); ?>

