<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/config/bootstrap.php';
ns_redirect_legacy_url('/ferramentas/calculadora-inss');
ns_render_page_start('tool:calculadora-inss');
?>
<main><div class="tool-page">
  <nav class="breadcrumb" aria-label="Navegação breadcrumb"><a href="<?= ns_escape(ns_href('/')) ?>">Início</a><span class="sep">›</span><a href="<?= ns_escape(ns_href('/ferramentas')) ?>">Ferramentas</a><span class="sep">›</span><span>Calculadora de INSS</span></nav>
  <?php ns_render_ad_slot('leaderboard'); ?>
  <div class="tool-header"><div class="tool-page-icon" style="background:linear-gradient(135deg,#f4f9ff,#dbe9ff);">🏛️</div><div><h1>Calculadora de INSS</h1><p>Calcule uma estimativa de desconto de INSS com base no salário bruto mensal.</p><span class="tag tag-green">Finanças</span></div></div>
  <div class="tool-box">
    <div class="form-row"><div class="form-group"><label for="inss-salario">Salário bruto mensal (R$)</label><input type="number" id="inss-salario" class="form-control" min="0" step="0.01" placeholder="Ex: 4500" /></div></div>
    <div class="form-row"><button type="button" class="btn btn-primary" onclick="runTool()">Calcular INSS</button><button type="button" class="btn btn-outline" onclick="clearTool()">Limpar</button><button type="button" class="copy-btn" onclick="copyTool(this)">Copiar resultado</button></div>
    <div class="notice notice-warn" id="tool-error" style="display:none;"><span>⚠️</span><span id="tool-error-text"></span></div>
    <div class="result-box" id="tool-result"><div class="result-label">Estimativa do INSS</div><div class="result-grid"><div class="result-item"><div class="label">Desconto estimado</div><div class="value" id="inss-desconto">-</div></div><div class="result-item"><div class="label">Alíquota usada</div><div class="value" id="inss-aliquota">-</div></div></div><div id="tool-detail" style="margin-top:1rem;color:var(--text2);"></div></div>
  </div>
  <?php ns_render_ad_slot('rectangle'); ?>
<div class="seo-content"><h2>O que é essa ferramenta</h2><p>A calculadora de INSS mostra uma estimativa do desconto previdenciário mensal sobre o salário bruto. Ela é útil para entender o impacto do desconto no holerite, planejar renda líquida e comparar propostas salariais.</p><p>O cálculo roda em JavaScript puro no navegador, o que ajuda a manter a página rápida, leve e fácil de usar em qualquer dispositivo. A estrutura também foi pensada para SEO, com conteúdo explicativo, headings claros e foco em intenção de busca real.</p><h2>Como usar</h2><p>Digite o salário bruto mensal e clique no botão de cálculo. A ferramenta aplica uma lógica simplificada por faixas e mostra o desconto estimado, além da alíquota principal considerada na simulação.</p><p>Se algum campo estiver vazio ou com valor inválido, a ferramenta mostra uma mensagem amigável antes de liberar o resultado. Depois, você pode copiar a resposta ou limpar tudo para uma nova simulação.</p><h2>Exemplo de uso</h2><p>Quem recebe R$ 4.500 por mês pode usar a calculadora para estimar quanto será destinado ao INSS e quanto isso afeta o valor líquido final do salário.</p><p>Esse contexto adicional torna a página mais útil para visitantes que chegam pela busca orgânica e precisam de uma resposta prática, mas também querem entender como aplicar o resultado.</p><h2>Perguntas frequentes</h2><h3>A conta é oficial?</h3><p>É uma estimativa prática para apoio e conferência inicial.</p><h3>Posso usar para comparar propostas de emprego?</h3><p>Sim. Ela ajuda bastante em análises salariais rápidas.</p><h3>A alíquota muda por faixa?</h3><p>Sim. A previdência usa faixas progressivas, e a ferramenta simplifica isso para uso rápido.</p></div>
  <div class="related-tools"><h2>Ferramentas relacionadas</h2><div class="related-grid"><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-imposto-renda')) ?>" class="related-card"><span class="related-card-icon">🧾</span> Imposto de Renda</a><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-salario-liquido')) ?>" class="related-card"><span class="related-card-icon">💼</span> Salário Líquido</a><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-fgts')) ?>" class="related-card"><span class="related-card-icon">📦</span> FGTS</a></div></div>
</div></main>
<script>
function showError(message){document.getElementById('tool-error-text').textContent=message;document.getElementById('tool-error').style.display='flex';document.getElementById('tool-result').classList.remove('show');}
function clearError(){document.getElementById('tool-error').style.display='none';}
function runTool(){const salario=parseFloat(document.getElementById('inss-salario').value);clearError();if(isNaN(salario)||salario<=0){showError('Informe um salário bruto válido maior que zero.');return;}let aliquota=0.075;if(salario>1412&&salario<=2666.68){aliquota=0.09;}else if(salario>2666.68&&salario<=4000.03){aliquota=0.12;}else if(salario>4000.03){aliquota=0.14;}const desconto=salario*aliquota;document.getElementById('inss-desconto').textContent='R$ '+fmtBRL(desconto);document.getElementById('inss-aliquota').textContent=fmtNum(aliquota*100,2)+'%';document.getElementById('tool-detail').textContent='Estimativa simplificada com base em faixas previdenciárias.';showResult('tool-result');}function clearTool(){document.getElementById('inss-salario').value='';['inss-desconto','inss-aliquota'].forEach(id=>document.getElementById(id).textContent='-');document.getElementById('tool-detail').textContent='';document.getElementById('tool-result').classList.remove('show');clearError();}function copyTool(button){if(!document.getElementById('tool-result').classList.contains('show')){showError('Calcule o INSS antes de copiar o resultado.');return;}copyToClipboard('INSS estimado: '+document.getElementById('inss-desconto').textContent,button);}
</script>
<?php ns_render_page_end(); ?>

