<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/config/bootstrap.php';
ns_redirect_legacy_url('/ferramentas/calculadora-cartao-credito');
ns_render_page_start('tool:calculadora-cartao-credito');
?>
<main><div class="tool-page">
  <nav class="breadcrumb" aria-label="Navegação breadcrumb"><a href="<?= ns_escape(ns_href('/')) ?>">Início</a><span class="sep">›</span><a href="<?= ns_escape(ns_href('/ferramentas')) ?>">Ferramentas</a><span class="sep">›</span><span>Calculadora de Cartão de Crédito</span></nav>
  <?php ns_render_ad_slot('leaderboard'); ?>
  <div class="tool-header"><div class="tool-page-icon" style="background:linear-gradient(135deg,#fff7f0,#ffe4cc);">💳</div><div><h1>Calculadora de Cartão de Crédito</h1><p>Simule juros de cartão de crédito a partir do valor da fatura, juros mensais e quantidade de meses.</p><span class="tag tag-green">Finanças</span></div></div>
  <div class="tool-box">
    <div class="form-row"><div class="form-group"><label for="cc-valor">Valor da fatura (R$)</label><input type="number" id="cc-valor" class="form-control" min="0" step="0.01" placeholder="Ex: 2500" /></div><div class="form-group"><label for="cc-juros">Juros ao mês (%)</label><input type="number" id="cc-juros" class="form-control" min="0" step="0.01" placeholder="Ex: 12" /></div><div class="form-group"><label for="cc-meses">Meses</label><input type="number" id="cc-meses" class="form-control" min="1" step="1" placeholder="Ex: 6" /></div></div>
    <div class="form-row"><button type="button" class="btn btn-primary" onclick="runTool()">Calcular fatura</button><button type="button" class="btn btn-outline" onclick="clearTool()">Limpar</button><button type="button" class="copy-btn" onclick="copyTool(this)">Copiar resultado</button></div>
    <div class="notice notice-warn" id="tool-error" style="display:none;"><span>⚠️</span><span id="tool-error-text"></span></div>
    <div class="result-box" id="tool-result"><div class="result-label">Simulação do cartão</div><div class="result-grid"><div class="result-item"><div class="label">Parcela estimada</div><div class="value" id="cc-parcela">-</div></div><div class="result-item"><div class="label">Total final</div><div class="value" id="cc-total">-</div></div></div><div id="tool-detail" style="margin-top:1rem;color:var(--text2);"></div></div>
  </div>
  <?php ns_render_ad_slot('rectangle'); ?>
<div class="seo-content"><h2>O que é essa ferramenta</h2><p>A calculadora de cartão de crédito ajuda a estimar o impacto dos juros sobre uma fatura ou saldo parcelado. Ela é útil para planejamento financeiro, renegociação e comparação entre pagar à vista, parcelar ou buscar alternativas de crédito.</p><p>O cálculo roda em JavaScript puro no navegador, o que ajuda a manter a página rápida, leve e fácil de usar em qualquer dispositivo. A estrutura também foi pensada para SEO, com conteúdo explicativo, headings claros e foco em intenção de busca real.</p><h2>Como usar</h2><p>Informe o valor da fatura, os juros mensais e o número de meses desejado. A ferramenta simula uma parcela estimada e mostra o total pago ao fim do período.</p><p>Se algum campo estiver vazio ou com valor inválido, a ferramenta mostra uma mensagem amigável antes de liberar o resultado. Depois, você pode copiar a resposta ou limpar tudo para uma nova simulação.</p><h2>Exemplo de uso</h2><p>Quem deseja parcelar uma fatura de R$ 2.500 com juros elevados pode usar a calculadora para entender rapidamente o peso real do parcelamento.</p><p>Esse contexto adicional torna a página mais útil para visitantes que chegam pela busca orgânica e precisam de uma resposta prática, mas também querem entender como aplicar o resultado.</p><h2>Perguntas frequentes</h2><h3>Serve para rotativo?</h3><p>Sim. A ferramenta é útil para simular cenários com juros altos.</p><h3>Posso comparar com empréstimo?</h3><p>Sim. Essa é uma das melhores formas de usar a ferramenta.</p><h3>A parcela é exata?</h3><p>É uma estimativa prática para análise e comparação.</p></div>
  <div class="related-tools"><h2>Ferramentas relacionadas</h2><div class="related-grid"><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-emprestimo')) ?>" class="related-card"><span class="related-card-icon">💳</span> Empréstimo</a><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-juros-atraso')) ?>" class="related-card"><span class="related-card-icon">📅</span> Juros por Atraso</a><a href="<?= ns_escape(ns_href('/ferramentas/juros-compostos')) ?>" class="related-card"><span class="related-card-icon">📈</span> Juros Compostos</a></div></div>
</div></main>
<script>
function showError(message){document.getElementById('tool-error-text').textContent=message;document.getElementById('tool-error').style.display='flex';document.getElementById('tool-result').classList.remove('show');}
function clearError(){document.getElementById('tool-error').style.display='none';}
function runTool(){const valor=parseFloat(document.getElementById('cc-valor').value);const juros=parseFloat(document.getElementById('cc-juros').value)/100;const meses=parseInt(document.getElementById('cc-meses').value,10);clearError();if(isNaN(valor)||isNaN(juros)||isNaN(meses)||valor<=0||juros<0||meses<=0){showError('Preencha valor, juros e meses com dados válidos.');return;}const parcela=juros===0?valor/meses:(valor*juros)/(1-Math.pow(1+juros,-meses));const total=parcela*meses;document.getElementById('cc-parcela').textContent='R$ '+fmtBRL(parcela);document.getElementById('cc-total').textContent='R$ '+fmtBRL(total);document.getElementById('tool-detail').textContent='Simulação útil para análise de parcelamento e comparação financeira.';showResult('tool-result');}function clearTool(){['cc-valor','cc-juros','cc-meses'].forEach(id=>document.getElementById(id).value='');['cc-parcela','cc-total'].forEach(id=>document.getElementById(id).textContent='-');document.getElementById('tool-detail').textContent='';document.getElementById('tool-result').classList.remove('show');clearError();}function copyTool(button){if(!document.getElementById('tool-result').classList.contains('show')){showError('Calcule a fatura antes de copiar o resultado.');return;}copyToClipboard('Parcela estimada: '+document.getElementById('cc-parcela').textContent,button);}
</script>
<?php ns_render_page_end(); ?>

