<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/config/bootstrap.php';
ns_redirect_legacy_url('/ferramentas/calculadora-rendimento-poupanca');
ns_render_page_start('tool:calculadora-rendimento-poupanca');
?>
<main><div class="tool-page">
  <nav class="breadcrumb" aria-label="Navegação breadcrumb"><a href="<?= ns_escape(ns_href('/')) ?>">Início</a><span class="sep">›</span><a href="<?= ns_escape(ns_href('/ferramentas')) ?>">Ferramentas</a><span class="sep">›</span><span>Calculadora de Rendimento da Poupança</span></nav>
  <?php ns_render_ad_slot('leaderboard'); ?>
  <div class="tool-header"><div class="tool-page-icon" style="background:linear-gradient(135deg,#eef8f0,#d7efdb);">🏦</div><div><h1>Calculadora de Rendimento da Poupança</h1><p>Simule o rendimento da poupança usando valor investido, taxa mensal e prazo da aplicação.</p><span class="tag tag-green">Finanças</span></div></div>
  <div class="tool-box">
    <div class="form-row"><div class="form-group"><label for="poupanca-valor">Valor aplicado (R$)</label><input type="number" id="poupanca-valor" class="form-control" min="0" step="0.01" placeholder="Ex: 1000" /></div><div class="form-group"><label for="poupanca-taxa">Taxa mensal (%)</label><input type="number" id="poupanca-taxa" class="form-control" min="0" step="0.01" placeholder="Ex: 0.5" /></div><div class="form-group"><label for="poupanca-meses">Prazo em meses</label><input type="number" id="poupanca-meses" class="form-control" min="1" step="1" placeholder="Ex: 12" /></div></div>
    <div class="form-row"><button type="button" class="btn btn-primary" onclick="runTool()">Calcular rendimento</button><button type="button" class="btn btn-outline" onclick="clearTool()">Limpar</button><button type="button" class="copy-btn" onclick="copyTool(this)">Copiar resultado</button></div>
    <div class="notice notice-warn" id="tool-error" style="display:none;"><span>⚠️</span><span id="tool-error-text"></span></div>
    <div class="result-box" id="tool-result"><div class="result-label">Simulação da poupança</div><div class="result-grid"><div class="result-item"><div class="label">Saldo final</div><div class="value" id="poupanca-total">-</div></div><div class="result-item"><div class="label">Rendimento</div><div class="value" id="poupanca-rendimento">-</div></div></div><div id="tool-detail" style="margin-top:1rem;color:var(--text2);"></div></div>
  </div>
  <?php ns_render_ad_slot('rectangle'); ?>
<div class="seo-content"><h2>O que é essa ferramenta</h2><p>A calculadora de rendimento da poupança ajuda a estimar quanto um valor aplicado pode render ao longo dos meses. Ela é útil para planejamento financeiro, comparação com outros investimentos e organização de metas.</p><p>O cálculo roda em JavaScript puro no navegador, o que ajuda a manter a página rápida, leve e fácil de usar em qualquer dispositivo. A estrutura também foi pensada para SEO, com conteúdo explicativo, headings claros e foco em intenção de busca real.</p><h2>Como usar</h2><p>Digite o valor aplicado, a taxa mensal desejada e a quantidade de meses. A ferramenta calcula o saldo final e o rendimento acumulado em uma simulação simples e prática.</p><p>Se algum campo estiver vazio ou com valor inválido, a ferramenta mostra uma mensagem amigável antes de liberar o resultado. Depois, você pode copiar a resposta ou limpar tudo para uma nova simulação.</p><h2>Exemplo de uso</h2><p>Se uma pessoa investir R$ 1.000 com taxa mensal de 0,5% durante 12 meses, a calculadora mostra o saldo final estimado e quanto foi ganho no período.</p><p>Esse contexto adicional torna a página mais útil para visitantes que chegam pela busca orgânica e precisam de uma resposta prática, mas também querem entender como aplicar o resultado.</p><h2>Perguntas frequentes</h2><h3>A taxa já vem preenchida?</h3><p>Não. Você informa a taxa que deseja usar na simulação.</p><h3>Serve para comparar com CDI?</h3><p>Sim. É útil para comparar cenários de investimento.</p><h3>A conta usa juros compostos?</h3><p>Sim. A simulação usa capitalização mensal sobre o valor acumulado.</p></div>
  <div class="related-tools"><h2>Ferramentas relacionadas</h2><div class="related-grid"><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-cdi')) ?>" class="related-card"><span class="related-card-icon">💹</span> CDI</a><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-investimento-mensal')) ?>" class="related-card"><span class="related-card-icon">📅</span> Investimento Mensal</a><a href="<?= ns_escape(ns_href('/ferramentas/juros-compostos')) ?>" class="related-card"><span class="related-card-icon">📈</span> Juros Compostos</a></div></div>
</div></main>
<script>
function showError(message){document.getElementById('tool-error-text').textContent=message;document.getElementById('tool-error').style.display='flex';document.getElementById('tool-result').classList.remove('show');}
function clearError(){document.getElementById('tool-error').style.display='none';}
function runTool(){const valor=parseFloat(document.getElementById('poupanca-valor').value);const taxa=parseFloat(document.getElementById('poupanca-taxa').value);const meses=parseInt(document.getElementById('poupanca-meses').value,10);clearError();if(isNaN(valor)||isNaN(taxa)||isNaN(meses)||valor<0||taxa<0||meses<=0){showError('Preencha valor, taxa e prazo com dados válidos.');return;}const total=valor*Math.pow(1+(taxa/100),meses);document.getElementById('poupanca-total').textContent='R$ '+fmtBRL(total);document.getElementById('poupanca-rendimento').textContent='R$ '+fmtBRL(total-valor);document.getElementById('tool-detail').textContent='Simulação com capitalização mensal para apoio educacional e financeiro.';showResult('tool-result');}function clearTool(){['poupanca-valor','poupanca-taxa','poupanca-meses'].forEach(id=>document.getElementById(id).value='');['poupanca-total','poupanca-rendimento'].forEach(id=>document.getElementById(id).textContent='-');document.getElementById('tool-detail').textContent='';document.getElementById('tool-result').classList.remove('show');clearError();}function copyTool(button){if(!document.getElementById('tool-result').classList.contains('show')){showError('Calcule o rendimento antes de copiar o resultado.');return;}copyToClipboard('Saldo final: '+document.getElementById('poupanca-total').textContent,button);}
</script>
<?php ns_render_page_end(); ?>

