<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/config/bootstrap.php';
ns_redirect_legacy_url('/ferramentas/calculadora-horas-trabalho');
ns_render_page_start('tool:calculadora-horas-trabalho');
?>
<main><div class="tool-page">
  <nav class="breadcrumb" aria-label="Navegação breadcrumb"><a href="<?= ns_escape(ns_href('/')) ?>">Início</a><span class="sep">›</span><a href="<?= ns_escape(ns_href('/ferramentas')) ?>">Ferramentas</a><span class="sep">›</span><span>Calculadora de Horas de Trabalho</span></nav>
  <?php ns_render_ad_slot('leaderboard'); ?>
  <div class="tool-header"><div class="tool-page-icon" style="background:linear-gradient(135deg,#f0f5ff,#d8e4ff);">🕒</div><div><h1>Calculadora de Horas de Trabalho</h1><p>Calcule o total de horas trabalhadas usando horário de entrada, saída e intervalo.</p><span class="tag tag-green">Finanças</span></div></div>
  <div class="tool-box">
    <div class="form-row"><div class="form-group"><label for="ht-entrada">Hora de entrada (08.00)</label><input type="number" id="ht-entrada" class="form-control" min="0" step="0.01" placeholder="Ex: 08.00" /></div><div class="form-group"><label for="ht-saida">Hora de saída (17.30)</label><input type="number" id="ht-saida" class="form-control" min="0" step="0.01" placeholder="Ex: 17.30" /></div><div class="form-group"><label for="ht-intervalo">Intervalo em horas</label><input type="number" id="ht-intervalo" class="form-control" min="0" step="0.01" placeholder="Ex: 1" /></div></div>
    <div class="form-row"><button type="button" class="btn btn-primary" onclick="runTool()">Calcular horas</button><button type="button" class="btn btn-outline" onclick="clearTool()">Limpar</button><button type="button" class="copy-btn" onclick="copyTool(this)">Copiar resultado</button></div>
    <div class="notice notice-warn" id="tool-error" style="display:none;"><span>⚠️</span><span id="tool-error-text"></span></div>
    <div class="result-box" id="tool-result"><div class="result-label">Jornada calculada</div><div class="result-grid"><div class="result-item"><div class="label">Horas líquidas</div><div class="value" id="ht-horas">-</div></div><div class="result-item"><div class="label">Minutos</div><div class="value" id="ht-minutos">-</div></div></div><div id="tool-detail" style="margin-top:1rem;color:var(--text2);"></div></div>
  </div>
  <?php ns_render_ad_slot('rectangle'); ?>
<div class="seo-content"><h2>O que é essa ferramenta</h2><p>A calculadora de horas de trabalho ajuda a descobrir a jornada líquida diária com base em entrada, saída e intervalo. Ela é útil para controle pessoal, conferência de rotina profissional, prestação de serviço e produtividade.</p><p>O cálculo roda em JavaScript puro no navegador, o que ajuda a manter a página rápida, leve e fácil de usar em qualquer dispositivo. A estrutura também foi pensada para SEO, com conteúdo explicativo, headings claros e foco em intenção de busca real.</p><h2>Como usar</h2><p>Digite a hora de entrada, a hora de saída e o intervalo em horas. A ferramenta calcula o tempo líquido trabalhado e mostra o resultado em horas e minutos.</p><p>Se algum campo estiver vazio ou com valor inválido, a ferramenta mostra uma mensagem amigável antes de liberar o resultado. Depois, você pode copiar a resposta ou limpar tudo para uma nova simulação.</p><h2>Exemplo de uso</h2><p>Se uma pessoa entra às 08.00, sai às 17.30 e faz 1 hora de intervalo, a calculadora mostra a jornada líquida, o que facilita organização e conferência.</p><p>Esse contexto adicional torna a página mais útil para visitantes que chegam pela busca orgânica e precisam de uma resposta prática, mas também querem entender como aplicar o resultado.</p><h2>Perguntas frequentes</h2><h3>Aceita meia hora?</h3><p>Sim. Você pode informar valores com decimais no formato usado na página.</p><h3>Serve para autônomos?</h3><p>Sim. É útil para qualquer rotina baseada em horas.</p><h3>O cálculo considera intervalo?</h3><p>Sim. O intervalo informado é descontado da jornada.</p></div>
  <div class="related-tools"><h2>Ferramentas relacionadas</h2><div class="related-grid"><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-salario-liquido')) ?>" class="related-card"><span class="related-card-icon">💼</span> Salário Líquido</a><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-roi')) ?>" class="related-card"><span class="related-card-icon">📈</span> ROI</a><a href="<?= ns_escape(ns_href('/ferramentas/contador-palavras')) ?>" class="related-card"><span class="related-card-icon">📄</span> Contador de Palavras</a></div></div>
</div></main>
<script>
function showError(message){document.getElementById('tool-error-text').textContent=message;document.getElementById('tool-error').style.display='flex';document.getElementById('tool-result').classList.remove('show');}
function clearError(){document.getElementById('tool-error').style.display='none';}
function toMinutes(value){const horas=Math.floor(value);const minutos=Math.round((value-horas)*100);return (horas*60)+minutos;}function runTool(){const entrada=parseFloat(document.getElementById('ht-entrada').value);const saida=parseFloat(document.getElementById('ht-saida').value);const intervalo=parseFloat(document.getElementById('ht-intervalo').value);clearError();if(isNaN(entrada)||isNaN(saida)||isNaN(intervalo)||intervalo<0){showError('Preencha entrada, saída e intervalo com valores válidos.');return;}const total=toMinutes(saida)-toMinutes(entrada)-(intervalo*60);if(total<=0){showError('A jornada líquida precisa ser maior que zero.');return;}document.getElementById('ht-horas').textContent=fmtNum(total/60,2)+' h';document.getElementById('ht-minutos').textContent=fmtNum(total,0)+' min';document.getElementById('tool-detail').textContent='O cálculo desconta o intervalo da diferença entre entrada e saída.';showResult('tool-result');}function clearTool(){['ht-entrada','ht-saida','ht-intervalo'].forEach(id=>document.getElementById(id).value='');['ht-horas','ht-minutos'].forEach(id=>document.getElementById(id).textContent='-');document.getElementById('tool-detail').textContent='';document.getElementById('tool-result').classList.remove('show');clearError();}function copyTool(button){if(!document.getElementById('tool-result').classList.contains('show')){showError('Calcule as horas antes de copiar o resultado.');return;}copyToClipboard('Horas trabalhadas: '+document.getElementById('ht-horas').textContent,button);}
</script>
<?php ns_render_page_end(); ?>

