<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/config/bootstrap.php';
ns_redirect_legacy_url('/ferramentas/calculadora-cdi');
ns_render_page_start('tool:calculadora-cdi');
?>
<main><div class="tool-page">
  <nav class="breadcrumb" aria-label="Navegação breadcrumb"><a href="<?= ns_escape(ns_href('/')) ?>">Início</a><span class="sep">›</span><a href="<?= ns_escape(ns_href('/ferramentas')) ?>">Ferramentas</a><span class="sep">›</span><span>Calculadora de CDI</span></nav>
  <?php ns_render_ad_slot('leaderboard'); ?>
  <div class="tool-header"><div class="tool-page-icon" style="background:linear-gradient(135deg,#f2f8ff,#dce9ff);">💹</div><div><h1>Calculadora de CDI</h1><p>Simule rendimento atrelado ao CDI usando valor investido, percentual do CDI e prazo.</p><span class="tag tag-green">Finanças</span></div></div>
  <div class="tool-box">
    <div class="form-row"><div class="form-group"><label for="cdi-valor">Valor investido (R$)</label><input type="number" id="cdi-valor" class="form-control" min="0" step="0.01" placeholder="Ex: 5000" /></div><div class="form-group"><label for="cdi-taxa">CDI anual (%)</label><input type="number" id="cdi-taxa" class="form-control" min="0" step="0.01" placeholder="Ex: 10.65" /></div><div class="form-group"><label for="cdi-percentual">% do CDI</label><input type="number" id="cdi-percentual" class="form-control" min="0" step="0.01" placeholder="Ex: 100" /></div><div class="form-group"><label for="cdi-meses">Prazo em meses</label><input type="number" id="cdi-meses" class="form-control" min="1" step="1" placeholder="Ex: 12" /></div></div>
    <div class="form-row"><button type="button" class="btn btn-primary" onclick="runTool()">Calcular CDI</button><button type="button" class="btn btn-outline" onclick="clearTool()">Limpar</button><button type="button" class="copy-btn" onclick="copyTool(this)">Copiar resultado</button></div>
    <div class="notice notice-warn" id="tool-error" style="display:none;"><span>⚠️</span><span id="tool-error-text"></span></div>
    <div class="result-box" id="tool-result"><div class="result-label">Simulação de rendimento</div><div class="result-grid"><div class="result-item"><div class="label">Saldo final</div><div class="value" id="cdi-total">-</div></div><div class="result-item"><div class="label">Rendimento</div><div class="value" id="cdi-rendimento">-</div></div></div><div id="tool-detail" style="margin-top:1rem;color:var(--text2);"></div></div>
  </div>
  <?php ns_render_ad_slot('rectangle'); ?>
<div class="seo-content"><h2>O que é essa ferramenta</h2><p>A calculadora de CDI ajuda a projetar o rendimento de aplicações atreladas a esse indicador, usando valor investido, percentual contratado e prazo da aplicação. Ela é útil para comparar produtos financeiros e planejar decisões de investimento.</p><p>O cálculo roda em JavaScript puro no navegador, o que ajuda a manter a página rápida, leve e fácil de usar em qualquer dispositivo. A estrutura também foi pensada para SEO, com conteúdo explicativo, headings claros e foco em intenção de busca real.</p><h2>Como usar</h2><p>Informe o valor inicial, a taxa anual de CDI, o percentual do CDI aplicado pelo investimento e o número de meses. A ferramenta faz uma simulação educacional e mostra saldo final e rendimento.</p><p>Se algum campo estiver vazio ou com valor inválido, a ferramenta mostra uma mensagem amigável antes de liberar o resultado. Depois, você pode copiar a resposta ou limpar tudo para uma nova simulação.</p><h2>Exemplo de uso</h2><p>Quem quer comparar um investimento de 100% do CDI com outro de 110% do CDI pode usar a calculadora para visualizar a diferença estimada no período desejado.</p><p>Esse contexto adicional torna a página mais útil para visitantes que chegam pela busca orgânica e precisam de uma resposta prática, mas também querem entender como aplicar o resultado.</p><h2>Perguntas frequentes</h2><h3>O cálculo é exato?</h3><p>É uma simulação prática, útil para comparação e planejamento inicial.</p><h3>Serve para CDB?</h3><p>Sim. É especialmente útil para produtos atrelados ao CDI.</p><h3>O prazo precisa estar em meses?</h3><p>Nesta versão, sim. A simulação foi padronizada em meses para facilitar o uso.</p></div>
  <div class="related-tools"><h2>Ferramentas relacionadas</h2><div class="related-grid"><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-rendimento-poupanca')) ?>" class="related-card"><span class="related-card-icon">🏦</span> Rendimento da Poupança</a><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-investimento-mensal')) ?>" class="related-card"><span class="related-card-icon">📅</span> Investimento Mensal</a><a href="<?= ns_escape(ns_href('/ferramentas/juros-compostos')) ?>" class="related-card"><span class="related-card-icon">📈</span> Juros Compostos</a></div></div>
</div></main>
<script>
function showError(message){document.getElementById('tool-error-text').textContent=message;document.getElementById('tool-error').style.display='flex';document.getElementById('tool-result').classList.remove('show');}
function clearError(){document.getElementById('tool-error').style.display='none';}
function runTool(){const valor=parseFloat(document.getElementById('cdi-valor').value);const taxa=parseFloat(document.getElementById('cdi-taxa').value);const percentual=parseFloat(document.getElementById('cdi-percentual').value);const meses=parseInt(document.getElementById('cdi-meses').value,10);clearError();if(isNaN(valor)||isNaN(taxa)||isNaN(percentual)||isNaN(meses)||valor<0||taxa<0||percentual<0||meses<=0){showError('Preencha todos os campos com valores válidos.');return;}const taxaMensal=((taxa*(percentual/100))/100)/12;const total=valor*Math.pow(1+taxaMensal,meses);document.getElementById('cdi-total').textContent='R$ '+fmtBRL(total);document.getElementById('cdi-rendimento').textContent='R$ '+fmtBRL(total-valor);document.getElementById('tool-detail').textContent='Simulação educacional com conversão simplificada de taxa anual para mensal.';showResult('tool-result');}function clearTool(){['cdi-valor','cdi-taxa','cdi-percentual','cdi-meses'].forEach(id=>document.getElementById(id).value='');['cdi-total','cdi-rendimento'].forEach(id=>document.getElementById(id).textContent='-');document.getElementById('tool-detail').textContent='';document.getElementById('tool-result').classList.remove('show');clearError();}function copyTool(button){if(!document.getElementById('tool-result').classList.contains('show')){showError('Calcule o CDI antes de copiar o resultado.');return;}copyToClipboard('Saldo final: '+document.getElementById('cdi-total').textContent,button);}
</script>
<?php ns_render_page_end(); ?>

