<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/config/bootstrap.php';
ns_redirect_legacy_url('/ferramentas/calculadora-inflacao');
ns_render_page_start('tool:calculadora-inflacao');
?>
<main><div class="tool-page">
  <nav class="breadcrumb" aria-label="Navegação breadcrumb"><a href="<?= ns_escape(ns_href('/')) ?>">Início</a><span class="sep">›</span><a href="<?= ns_escape(ns_href('/ferramentas')) ?>">Ferramentas</a><span class="sep">›</span><span>Calculadora de Inflação</span></nav>
  <?php ns_render_ad_slot('leaderboard'); ?>
  <div class="tool-header"><div class="tool-page-icon" style="background:linear-gradient(135deg,#fff4f1,#ffd7ce);">📈</div><div><h1>Calculadora de Inflação</h1><p>Atualize um valor aplicando uma taxa de inflação para estimar perda de poder de compra ou reajuste.</p><span class="tag tag-green">Finanças</span></div></div>
  <div class="tool-box">
    <div class="form-row"><div class="form-group"><label for="inflacao-valor">Valor inicial (R$)</label><input type="number" id="inflacao-valor" class="form-control" min="0" step="0.01" placeholder="Ex: 1000" /></div><div class="form-group"><label for="inflacao-taxa">Inflação (%)</label><input type="number" id="inflacao-taxa" class="form-control" min="0" step="0.01" placeholder="Ex: 5.2" /></div></div>
    <div class="form-row"><button type="button" class="btn btn-primary" onclick="runTool()">Calcular inflação</button><button type="button" class="btn btn-outline" onclick="clearTool()">Limpar</button><button type="button" class="copy-btn" onclick="copyTool(this)">Copiar resultado</button></div>
    <div class="notice notice-warn" id="tool-error" style="display:none;"><span>⚠️</span><span id="tool-error-text"></span></div>
    <div class="result-box" id="tool-result"><div class="result-label">Valor ajustado</div><div class="result-grid"><div class="result-item"><div class="label">Valor ajustado</div><div class="value" id="inflacao-total">-</div></div><div class="result-item"><div class="label">Variação</div><div class="value" id="inflacao-aumento">-</div></div></div><div id="tool-detail" style="margin-top:1rem;color:var(--text2);"></div></div>
  </div>
  <?php ns_render_ad_slot('rectangle'); ?>
<div class="seo-content"><h2>O que é essa ferramenta</h2><p>A calculadora de inflação ajuda a simular como um valor muda depois da aplicação de uma taxa inflacionária. Ela é útil para comparar preços, revisar orçamento e entender perda de poder de compra.</p><p>O cálculo roda em JavaScript puro no navegador, o que ajuda a manter a página rápida, leve e fácil de usar em qualquer dispositivo. A estrutura também foi pensada para SEO, com conteúdo explicativo, headings claros e foco em intenção de busca real.</p><h2>Como usar</h2><p>Digite o valor inicial e a taxa de inflação desejada. A ferramenta calcula a variação em reais e mostra o valor ajustado com resposta imediata.</p><p>Se algum campo estiver vazio ou com valor inválido, a ferramenta mostra uma mensagem amigável antes de liberar o resultado. Depois, você pode copiar a resposta ou limpar tudo para uma nova simulação.</p><h2>Exemplo de uso</h2><p>Se um produto custava R$ 1.000 e a inflação considerada foi de 5,2%, a ferramenta mostra o novo valor aproximado e quanto isso representa de aumento.</p><p>Esse contexto adicional torna a página mais útil para visitantes que chegam pela busca orgânica e precisam de uma resposta prática, mas também querem entender como aplicar o resultado.</p><h2>Perguntas frequentes</h2><h3>Posso usar qualquer taxa?</h3><p>Sim. A ferramenta aplica a taxa percentual informada pelo usuário.</p><h3>Serve para reajuste contratual?</h3><p>Sim, como apoio de simulação e conferência.</p><h3>É diferente de correção monetária?</h3><p>Na prática podem se relacionar, mas aqui o foco é a taxa inflacionária informada.</p></div>
  <div class="related-tools"><h2>Ferramentas relacionadas</h2><div class="related-grid"><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-correcao-monetaria')) ?>" class="related-card"><span class="related-card-icon">📊</span> Correção Monetária</a><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-aluguel-reajuste')) ?>" class="related-card"><span class="related-card-icon">🏠</span> Reajuste de Aluguel</a><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-rendimento-poupanca')) ?>" class="related-card"><span class="related-card-icon">🏦</span> Rendimento da Poupança</a></div></div>
</div></main>
<script>
function showError(message){document.getElementById('tool-error-text').textContent=message;document.getElementById('tool-error').style.display='flex';document.getElementById('tool-result').classList.remove('show');}
function clearError(){document.getElementById('tool-error').style.display='none';}
function runTool(){const valor=parseFloat(document.getElementById('inflacao-valor').value);const taxa=parseFloat(document.getElementById('inflacao-taxa').value);clearError();if(isNaN(valor)||isNaN(taxa)||valor<0||taxa<0){showError('Informe valor e inflação com números válidos.');return;}const aumento=valor*(taxa/100);const total=valor+aumento;document.getElementById('inflacao-total').textContent='R$ '+fmtBRL(total);document.getElementById('inflacao-aumento').textContent='R$ '+fmtBRL(aumento);document.getElementById('tool-detail').textContent='Ajuste baseado na taxa inflacionária informada.';showResult('tool-result');}function clearTool(){['inflacao-valor','inflacao-taxa'].forEach(id=>document.getElementById(id).value='');['inflacao-total','inflacao-aumento'].forEach(id=>document.getElementById(id).textContent='-');document.getElementById('tool-detail').textContent='';document.getElementById('tool-result').classList.remove('show');clearError();}function copyTool(button){if(!document.getElementById('tool-result').classList.contains('show')){showError('Calcule a inflação antes de copiar o resultado.');return;}copyToClipboard('Valor ajustado: '+document.getElementById('inflacao-total').textContent,button);}
</script>
<?php ns_render_page_end(); ?>

