<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/config/bootstrap.php';
ns_redirect_legacy_url('/ferramentas/calculadora-roi');
ns_render_page_start('tool:calculadora-roi');
?>
<main><div class="tool-page">
  <nav class="breadcrumb" aria-label="Navegação breadcrumb"><a href="<?= ns_escape(ns_href('/')) ?>">Início</a><span class="sep">›</span><a href="<?= ns_escape(ns_href('/ferramentas')) ?>">Ferramentas</a><span class="sep">›</span><span>Calculadora de ROI</span></nav>
  <?php ns_render_ad_slot('leaderboard'); ?>
  <div class="tool-header"><div class="tool-page-icon" style="background:linear-gradient(135deg,#e9fbf5,#c9f2df);">📈</div><div><h1>Calculadora de ROI Online</h1><p>Calcule o retorno sobre investimento de forma rápida com custo, receita e percentual final de desempenho.</p><span class="tag tag-green">Finanças</span></div></div>
  <div class="tool-box">
    <div class="form-row"><div class="form-group"><label for="roi-investimento">Investimento (R$)</label><input type="number" id="roi-investimento" class="form-control" min="0" step="0.01" /></div><div class="form-group"><label for="roi-retorno">Retorno obtido (R$)</label><input type="number" id="roi-retorno" class="form-control" min="0" step="0.01" /></div></div>
    <div class="form-row"><button type="button" class="btn btn-primary" onclick="calcularROI()">Calcular ROI</button><button type="button" class="btn btn-outline" onclick="limparROI()">Limpar</button><button type="button" class="copy-btn" onclick="copiarROI(this)">Copiar resultado</button></div>
    <div class="notice notice-warn" id="erro-roi" style="display:none;"><span>⚠️</span><span id="erro-roi-texto"></span></div>
    <div class="result-box" id="resultado-roi"><div class="result-grid"><div class="result-item"><div class="label">ROI</div><div class="value" id="roi-percentual">—</div></div><div class="result-item"><div class="label">Lucro líquido</div><div class="value" id="roi-lucro">—</div></div></div><div id="roi-detalhe" style="margin-top:1rem;color:var(--text2);"></div></div>
  </div>
  <?php ns_render_ad_slot('rectangle'); ?>
  <div class="seo-content"><h2>O que é essa ferramenta</h2><p>A calculadora de ROI é usada para medir o retorno sobre investimento de uma ação, campanha, projeto ou operação. Ela ajuda a responder se o dinheiro investido trouxe ganho real e qual foi o percentual desse retorno.</p><p>É uma ferramenta muito buscada por profissionais de marketing, gestores, empreendedores e analistas financeiros. Como a lógica roda no navegador, o cálculo sai sem atraso e mantém a aplicação leve.</p><h2>Como usar</h2><p>Informe o valor investido e o retorno total obtido. Depois clique em calcular ROI. A ferramenta mostra o lucro líquido e o percentual de retorno. Se o investimento for zero ou inválido, a página exibe uma mensagem amigável antes de qualquer cálculo.</p><p>O botão copiar resultado é útil para relatórios, apresentações e comparações de campanhas.</p><h2>Exemplo de uso</h2><p>Se o investimento foi de R$ 1.000 e o retorno total foi de R$ 1.500, o lucro líquido é de R$ 500 e o ROI é de 50%. Isso permite comparar ações diferentes com um critério simples e direto.</p><p>Apesar de ser uma métrica importante, o ROI deve ser interpretado junto de prazo, risco e contexto do projeto.</p><h2>Perguntas frequentes</h2><h3>Qual fórmula é usada?</h3><p>ROI = (retorno - investimento) ÷ investimento × 100.</p><h3>O retorno informado deve ser bruto?</h3><p>Nesta ferramenta, você pode inserir o retorno total obtido para calcular o ganho relativo ao investimento inicial.</p><h3>ROI negativo é possível?</h3><p>Sim. Se o retorno for menor que o investimento, o ROI será negativo.</p></div>
  <div class="related-tools"><h2>Ferramentas relacionadas</h2><div class="related-grid"><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-break-even')) ?>" class="related-card"><span class="related-card-icon">💹</span> Break Even</a><a href="<?= ns_escape(ns_href('/ferramentas/juros-compostos')) ?>" class="related-card"><span class="related-card-icon">📈</span> Juros Compostos</a><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-desconto')) ?>" class="related-card"><span class="related-card-icon">🏷️</span> Desconto</a></div></div>
</div></main>
<script>
function erroROI(msg){document.getElementById('erro-roi-texto').textContent=msg;document.getElementById('erro-roi').style.display='flex';document.getElementById('resultado-roi').classList.remove('show');}
function limparErroROI(){document.getElementById('erro-roi').style.display='none';}
function calcularROI(){const investimento=parseFloat(document.getElementById('roi-investimento').value);const retorno=parseFloat(document.getElementById('roi-retorno').value);limparErroROI();if(isNaN(investimento)||isNaN(retorno)||investimento<=0){erroROI('Informe investimento válido e maior que zero, além do retorno obtido.');return;}const lucro=retorno-investimento;const roi=(lucro/investimento)*100;document.getElementById('roi-percentual').textContent=fmtNum(roi,2)+'%';document.getElementById('roi-lucro').textContent='R$ '+fmtBRL(lucro);document.getElementById('roi-detalhe').textContent='O cálculo compara lucro líquido com o valor investido.';showResult('resultado-roi');}
function limparROI(){document.getElementById('roi-investimento').value='';document.getElementById('roi-retorno').value='';document.getElementById('resultado-roi').classList.remove('show');limparErroROI();}
function copiarROI(button){if(!document.getElementById('resultado-roi').classList.contains('show')){erroROI('Calcule o ROI antes de copiar o resultado.');return;}copyToClipboard('ROI: '+document.getElementById('roi-percentual').textContent+'\nLucro: '+document.getElementById('roi-lucro').textContent,button);}
</script>
<?php ns_render_page_end(); ?>
