<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/config/bootstrap.php';
ns_redirect_legacy_url('/ferramentas/calculadora-break-even');
ns_render_page_start('tool:calculadora-break-even');
?>
<main><div class="tool-page">
  <nav class="breadcrumb" aria-label="Navegação breadcrumb"><a href="<?= ns_escape(ns_href('/')) ?>">Início</a><span class="sep">›</span><a href="<?= ns_escape(ns_href('/ferramentas')) ?>">Ferramentas</a><span class="sep">›</span><span>Calculadora de Break Even</span></nav>
  <?php ns_render_ad_slot('leaderboard'); ?>
  <div class="tool-header"><div class="tool-page-icon" style="background:linear-gradient(135deg,#eefaf1,#d1f0db);">💹</div><div><h1>Calculadora de Break Even</h1><p>Descubra quantas vendas ou unidades são necessárias para atingir o ponto de equilíbrio do seu negócio.</p><span class="tag tag-green">Finanças</span></div></div>
  <div class="tool-box">
    <div class="form-row"><div class="form-group"><label for="be-fixo">Custos fixos (R$)</label><input type="number" id="be-fixo" class="form-control" min="0" step="0.01" /></div><div class="form-group"><label for="be-preco">Preço por unidade (R$)</label><input type="number" id="be-preco" class="form-control" min="0" step="0.01" /></div><div class="form-group"><label for="be-variavel">Custo variável por unidade (R$)</label><input type="number" id="be-variavel" class="form-control" min="0" step="0.01" /></div></div>
    <div class="form-row"><button type="button" class="btn btn-primary" onclick="calcularBreakEven()">Calcular break even</button><button type="button" class="btn btn-outline" onclick="limparBreakEven()">Limpar</button><button type="button" class="copy-btn" onclick="copiarBreakEven(this)">Copiar resultado</button></div>
    <div class="notice notice-warn" id="erro-be" style="display:none;"><span>⚠️</span><span id="erro-be-texto"></span></div>
    <div class="result-box" id="resultado-be"><div class="result-grid"><div class="result-item"><div class="label">Ponto de equilíbrio</div><div class="value" id="be-unidades">—</div></div><div class="result-item"><div class="label">Faturamento necessário</div><div class="value" id="be-faturamento">—</div></div></div><div id="be-detalhe" style="margin-top:1rem;color:var(--text2);"></div></div>
  </div>
  <?php ns_render_ad_slot('rectangle'); ?>
  <div class="seo-content"><h2>O que é essa ferramenta</h2><p>A calculadora de break even, também chamada de calculadora de ponto de equilíbrio, mostra quantas unidades precisam ser vendidas para que a receita cubra todos os custos. É uma métrica essencial para negócios físicos, digitais, indústrias, serviços e operações comerciais em geral.</p><p>O cálculo ajuda a entender viabilidade, meta mínima de vendas e margem operacional. Como a conta roda direto no navegador, o resultado sai rápido e sem custo de processamento no servidor.</p><h2>Como usar</h2><p>Digite os custos fixos totais, o preço de venda por unidade e o custo variável por unidade. Depois clique em calcular. A ferramenta divide os custos fixos pela margem de contribuição unitária, que é o preço menos o custo variável.</p><p>Se o preço for menor ou igual ao custo variável, o sistema mostra uma validação, porque não existe margem positiva para atingir o equilíbrio.</p><h2>Exemplo de uso</h2><p>Se o custo fixo é R$ 5.000, o preço por unidade é R$ 100 e o custo variável é R$ 60, a margem de contribuição é R$ 40. O break even fica em 125 unidades. Isso mostra o mínimo necessário para empatar a operação antes de gerar lucro.</p><p>Esse tipo de análise é útil para precificação, metas mensais e tomada de decisão em campanhas de venda.</p><h2>Perguntas frequentes</h2><h3>O que é margem de contribuição?</h3><p>É a diferença entre o preço de venda por unidade e o custo variável por unidade.</p><h3>Se o preço for igual ao custo variável, há break even?</h3><p>Não. Nesse caso a margem de contribuição é zero, então o ponto de equilíbrio não é atingível.</p><h3>Serve para serviços?</h3><p>Sim. Desde que você consiga estimar custo fixo, custo variável e preço médio por venda.</p></div>
  <div class="related-tools"><h2>Ferramentas relacionadas</h2><div class="related-grid"><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-roi')) ?>" class="related-card"><span class="related-card-icon">📈</span> ROI</a><a href="<?= ns_escape(ns_href('/ferramentas/simulador-financiamento')) ?>" class="related-card"><span class="related-card-icon">🏠</span> Financiamento</a><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-desconto')) ?>" class="related-card"><span class="related-card-icon">🏷️</span> Desconto</a></div></div>
</div></main>
<script>
function erroBE(msg){document.getElementById('erro-be-texto').textContent=msg;document.getElementById('erro-be').style.display='flex';document.getElementById('resultado-be').classList.remove('show');}
function limparErroBE(){document.getElementById('erro-be').style.display='none';}
function calcularBreakEven(){const fixo=parseFloat(document.getElementById('be-fixo').value);const preco=parseFloat(document.getElementById('be-preco').value);const variavel=parseFloat(document.getElementById('be-variavel').value);limparErroBE();if(isNaN(fixo)||isNaN(preco)||isNaN(variavel)||fixo<0||preco<=0||variavel<0){erroBE('Preencha custos e preço com valores válidos.');return;}const margem=preco-variavel;if(margem<=0){erroBE('O preço por unidade precisa ser maior que o custo variável.');return;}const unidades=fixo/margem;const faturamento=unidades*preco;document.getElementById('be-unidades').textContent=fmtNum(unidades,2)+' un.';document.getElementById('be-faturamento').textContent='R$ '+fmtBRL(faturamento);document.getElementById('be-detalhe').textContent='Margem de contribuição unitária: R$ '+fmtBRL(margem)+'.';showResult('resultado-be');}
function limparBreakEven(){document.getElementById('be-fixo').value='';document.getElementById('be-preco').value='';document.getElementById('be-variavel').value='';document.getElementById('resultado-be').classList.remove('show');limparErroBE();}
function copiarBreakEven(button){if(!document.getElementById('resultado-be').classList.contains('show')){erroBE('Calcule o ponto de equilíbrio antes de copiar o resultado.');return;}copyToClipboard('Break even: '+document.getElementById('be-unidades').textContent+'\nFaturamento necessário: '+document.getElementById('be-faturamento').textContent,button);}
</script>
<?php ns_render_page_end(); ?>
