<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/config/bootstrap.php';
ns_redirect_legacy_url('/ferramentas/calculadora-salario-liquido');
ns_render_page_start('tool:calculadora-salario-liquido');
?>
<main><div class="tool-page">
  <nav class="breadcrumb" aria-label="Navegação breadcrumb"><a href="<?= ns_escape(ns_href('/')) ?>">Início</a><span class="sep">›</span><a href="<?= ns_escape(ns_href('/ferramentas')) ?>">Ferramentas</a><span class="sep">›</span><span>Calculadora de Salário Líquido</span></nav>
  <?php ns_render_ad_slot('leaderboard'); ?>
  <div class="tool-header"><div class="tool-page-icon" style="background:linear-gradient(135deg,#eef9f2,#d8f0e0);">💼</div><div><h1>Calculadora de Salário Líquido</h1><p>Estime o salário líquido usando salário bruto, INSS, imposto e desconto adicional.</p><span class="tag tag-green">Finanças</span></div></div>
  <div class="tool-box">
    <div class="form-row"><div class="form-group"><label for="sl-bruto">Salário bruto (R$)</label><input type="number" id="sl-bruto" class="form-control" min="0" step="0.01" placeholder="Ex: 5000" /></div><div class="form-group"><label for="sl-inss">INSS (R$)</label><input type="number" id="sl-inss" class="form-control" min="0" step="0.01" placeholder="Ex: 550" /></div><div class="form-group"><label for="sl-ir">Imposto de renda (R$)</label><input type="number" id="sl-ir" class="form-control" min="0" step="0.01" placeholder="Ex: 320" /></div><div class="form-group"><label for="sl-outros">Outros descontos (R$)</label><input type="number" id="sl-outros" class="form-control" min="0" step="0.01" placeholder="Ex: 150" /></div></div>
    <div class="form-row"><button type="button" class="btn btn-primary" onclick="runTool()">Calcular salário</button><button type="button" class="btn btn-outline" onclick="clearTool()">Limpar</button><button type="button" class="copy-btn" onclick="copyTool(this)">Copiar resultado</button></div>
    <div class="notice notice-warn" id="tool-error" style="display:none;"><span>⚠️</span><span id="tool-error-text"></span></div>
    <div class="result-box" id="tool-result"><div class="result-label">Estimativa do salário líquido</div><div class="result-grid"><div class="result-item"><div class="label">Salário líquido</div><div class="value" id="sl-liquido">-</div></div><div class="result-item"><div class="label">Total de descontos</div><div class="value" id="sl-descontos">-</div></div></div><div id="tool-detail" style="margin-top:1rem;color:var(--text2);"></div></div>
  </div>
  <?php ns_render_ad_slot('rectangle'); ?>
<div class="seo-content"><h2>O que é essa ferramenta</h2><p>A calculadora de salário líquido mostra quanto sobra do salário bruto depois dos principais descontos informados. Ela é útil para conferência de holerite, comparação de propostas e organização financeira.</p><p>O cálculo roda em JavaScript puro no navegador, o que ajuda a manter a página rápida, leve e fácil de usar em qualquer dispositivo. A estrutura também foi pensada para SEO, com conteúdo explicativo, headings claros e foco em intenção de busca real.</p><h2>Como usar</h2><p>Digite o salário bruto e os descontos conhecidos, como INSS, imposto de renda e outros abatimentos. A ferramenta soma os descontos e exibe o valor líquido final.</p><p>Se algum campo estiver vazio ou com valor inválido, a ferramenta mostra uma mensagem amigável antes de liberar o resultado. Depois, você pode copiar a resposta ou limpar tudo para uma nova simulação.</p><h2>Exemplo de uso</h2><p>Se uma pessoa recebe R$ 5.000 brutos e tem R$ 1.020 em descontos totais, a calculadora mostra o salário líquido estimado e ajuda na organização do orçamento.</p><p>Esse contexto adicional torna a página mais útil para visitantes que chegam pela busca orgânica e precisam de uma resposta prática, mas também querem entender como aplicar o resultado.</p><h2>Perguntas frequentes</h2><h3>Posso usar valores reais do holerite?</h3><p>Sim. A ferramenta funciona muito bem quando você já conhece os descontos.</p><h3>Serve para planejamento de renda?</h3><p>Sim. Ela ajuda a visualizar quanto realmente entra no mês.</p><h3>Substitui folha oficial?</h3><p>Não. É uma ferramenta de apoio e conferência.</p></div>
  <div class="related-tools"><h2>Ferramentas relacionadas</h2><div class="related-grid"><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-imposto-renda')) ?>" class="related-card"><span class="related-card-icon">🧾</span> Imposto de Renda</a><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-inss')) ?>" class="related-card"><span class="related-card-icon">🏛️</span> INSS</a><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-fgts')) ?>" class="related-card"><span class="related-card-icon">📦</span> FGTS</a></div></div>
</div></main>
<script>
function showError(message){document.getElementById('tool-error-text').textContent=message;document.getElementById('tool-error').style.display='flex';document.getElementById('tool-result').classList.remove('show');}
function clearError(){document.getElementById('tool-error').style.display='none';}
function runTool(){const bruto=parseFloat(document.getElementById('sl-bruto').value);const inss=parseFloat(document.getElementById('sl-inss').value)||0;const ir=parseFloat(document.getElementById('sl-ir').value)||0;const outros=parseFloat(document.getElementById('sl-outros').value)||0;clearError();if(isNaN(bruto)||bruto<=0||isNaN(inss)||inss<0||isNaN(ir)||ir<0||isNaN(outros)||outros<0){showError('Preencha salário e descontos com valores válidos.');return;}const descontos=inss+ir+outros;const liquido=bruto-descontos;document.getElementById('sl-liquido').textContent='R$ '+fmtBRL(liquido);document.getElementById('sl-descontos').textContent='R$ '+fmtBRL(descontos);document.getElementById('tool-detail').textContent='Estimativa direta com base nos descontos informados pelo usuário.';showResult('tool-result');}function clearTool(){['sl-bruto','sl-inss','sl-ir','sl-outros'].forEach(id=>document.getElementById(id).value='');['sl-liquido','sl-descontos'].forEach(id=>document.getElementById(id).textContent='-');document.getElementById('tool-detail').textContent='';document.getElementById('tool-result').classList.remove('show');clearError();}function copyTool(button){if(!document.getElementById('tool-result').classList.contains('show')){showError('Calcule o salário líquido antes de copiar o resultado.');return;}copyToClipboard('Salário líquido: '+document.getElementById('sl-liquido').textContent,button);}
</script>
<?php ns_render_page_end(); ?>

