<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/config/bootstrap.php';
ns_redirect_legacy_url('/ferramentas/calculadora-correcao-monetaria');
ns_render_page_start('tool:calculadora-correcao-monetaria');
?>
<main><div class="tool-page">
  <nav class="breadcrumb" aria-label="Navegação breadcrumb"><a href="<?= ns_escape(ns_href('/')) ?>">Início</a><span class="sep">›</span><a href="<?= ns_escape(ns_href('/ferramentas')) ?>">Ferramentas</a><span class="sep">›</span><span>Calculadora de Correção Monetária</span></nav>
  <?php ns_render_ad_slot('leaderboard'); ?>
  <div class="tool-header"><div class="tool-page-icon" style="background:linear-gradient(135deg,#f4f8ff,#dfe8ff);">📊</div><div><h1>Calculadora de Correção Monetária</h1><p>Corrija um valor aplicando uma taxa percentual para simular atualização monetária.</p><span class="tag tag-green">Finanças</span></div></div>
  <div class="tool-box">
    <div class="form-row"><div class="form-group"><label for="cm-valor">Valor original (R$)</label><input type="number" id="cm-valor" class="form-control" min="0" step="0.01" placeholder="Ex: 1000" /></div><div class="form-group"><label for="cm-taxa">Taxa de correção (%)</label><input type="number" id="cm-taxa" class="form-control" min="0" step="0.01" placeholder="Ex: 6.5" /></div></div>
    <div class="form-row"><button type="button" class="btn btn-primary" onclick="runTool()">Calcular correção</button><button type="button" class="btn btn-outline" onclick="clearTool()">Limpar</button><button type="button" class="copy-btn" onclick="copyTool(this)">Copiar resultado</button></div>
    <div class="notice notice-warn" id="tool-error" style="display:none;"><span>⚠️</span><span id="tool-error-text"></span></div>
    <div class="result-box" id="tool-result"><div class="result-label">Valor corrigido</div><div class="result-grid"><div class="result-item"><div class="label">Valor corrigido</div><div class="value" id="cm-corrigido">-</div></div><div class="result-item"><div class="label">Acréscimo</div><div class="value" id="cm-aumento">-</div></div></div><div id="tool-detail" style="margin-top:1rem;color:var(--text2);"></div></div>
  </div>
  <?php ns_render_ad_slot('rectangle'); ?>
<div class="seo-content"><h2>O que é essa ferramenta</h2><p>A calculadora de correção monetária serve para atualizar um valor com base em uma taxa percentual informada. Ela é útil para análises financeiras, revisão de contratos e comparação de valores antigos.</p><p>O cálculo roda em JavaScript puro no navegador, o que ajuda a manter a página rápida, leve e fácil de usar em qualquer dispositivo. A estrutura também foi pensada para SEO, com conteúdo explicativo, headings claros e foco em intenção de busca real.</p><h2>Como usar</h2><p>Digite o valor original e a taxa percentual desejada. A ferramenta calcula o acréscimo e mostra quanto o valor passa a representar depois da correção aplicada.</p><p>Se algum campo estiver vazio ou com valor inválido, a ferramenta mostra uma mensagem amigável antes de liberar o resultado. Depois, você pode copiar a resposta ou limpar tudo para uma nova simulação.</p><h2>Exemplo de uso</h2><p>Se um crédito de R$ 1.000 precisar ser atualizado por uma taxa de 6,5%, a ferramenta mostra o novo valor e o ganho correspondente.</p><p>Esse contexto adicional torna a página mais útil para visitantes que chegam pela busca orgânica e precisam de uma resposta prática, mas também querem entender como aplicar o resultado.</p><h2>Perguntas frequentes</h2><h3>Substitui índice oficial?</h3><p>Não. É uma simulação prática baseada na taxa informada pelo usuário.</p><h3>Posso usar para contratos?</h3><p>Sim, como apoio de conferência inicial e planejamento.</p><h3>O cálculo aceita taxa decimal?</h3><p>Sim. Você pode informar porcentagens com casas decimais.</p></div>
  <div class="related-tools"><h2>Ferramentas relacionadas</h2><div class="related-grid"><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-inflacao')) ?>" class="related-card"><span class="related-card-icon">📈</span> Inflação</a><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-aluguel-reajuste')) ?>" class="related-card"><span class="related-card-icon">🏠</span> Reajuste de Aluguel</a><a href="<?= ns_escape(ns_href('/ferramentas/calculadora-juros-atraso')) ?>" class="related-card"><span class="related-card-icon">📅</span> Juros por Atraso</a></div></div>
</div></main>
<script>
function showError(message){document.getElementById('tool-error-text').textContent=message;document.getElementById('tool-error').style.display='flex';document.getElementById('tool-result').classList.remove('show');}
function clearError(){document.getElementById('tool-error').style.display='none';}
function runTool(){const valor=parseFloat(document.getElementById('cm-valor').value);const taxa=parseFloat(document.getElementById('cm-taxa').value);clearError();if(isNaN(valor)||isNaN(taxa)||valor<0||taxa<0){showError('Informe valor e taxa com números válidos.');return;}const aumento=valor*(taxa/100);const total=valor+aumento;document.getElementById('cm-corrigido').textContent='R$ '+fmtBRL(total);document.getElementById('cm-aumento').textContent='R$ '+fmtBRL(aumento);document.getElementById('tool-detail').textContent='Cálculo simples de correção baseado na taxa percentual informada.';showResult('tool-result');}function clearTool(){['cm-valor','cm-taxa'].forEach(id=>document.getElementById(id).value='');['cm-corrigido','cm-aumento'].forEach(id=>document.getElementById(id).textContent='-');document.getElementById('tool-detail').textContent='';document.getElementById('tool-result').classList.remove('show');clearError();}function copyTool(button){if(!document.getElementById('tool-result').classList.contains('show')){showError('Calcule a correção antes de copiar o resultado.');return;}copyToClipboard('Valor corrigido: '+document.getElementById('cm-corrigido').textContent,button);}
</script>
<?php ns_render_page_end(); ?>

